/**
 * HariKita Invitation Studio — Cover Templates
 */
import type { SectionTemplate } from '../section-templates';
import { fadeIn, floatAnim, swayAnim, staticAnim, nodeBase, tfm, PP, LP, VP, AP, CP, PLP } from './helpers';

export const COVER_TEMPLATES: SectionTemplate[] = [
  {
    id: 'cover-romantic',
    sectionId: 'cover',
    name: 'Romantis Klasik',
    thumbnail: '🌸',
    description: 'Cover elegan dengan foto couple besar dan ornamen bunga',
    nodes: [
      { name: 'Background Foto', ...nodeBase('background'), transform: tfm(0,0,100,100), animation: staticAnim(), kind: 'image', config: { src: PP, fit: 'cover' } },
      { name: 'Bismillah / Opening', ...nodeBase('content'), transform: tfm(10,38,80,8), animation: fadeIn(0), kind: 'text', config: { text: 'بِسْمِ اللّٰهِ الرَّحْمٰنِ الرَّحِيْمِ', color: '#C5A880', fontSize: 18, align: 'center', fontFamily: 'Amiri' } },
      { name: 'Label Undangan', ...nodeBase('content'), transform: tfm(10,48,80,6), animation: fadeIn(300), kind: 'text', config: { text: 'Undangan Pernikahan', color: '#FAF8F5', fontSize: 13, align: 'center', fontFamily: 'Plus Jakarta Sans', letterSpacing: 2 } },
      { name: 'Nama Pengantin', ...nodeBase('content'), transform: tfm(5,55,90,18), animation: fadeIn(600), kind: 'text', config: { text: 'Ananda & Bintang', color: '#FAF8F5', fontSize: 48, align: 'center', fontFamily: 'Great Vibes' } },
      { name: 'Tanggal Pernikahan', ...nodeBase('content'), transform: tfm(15,74,70,7), animation: fadeIn(900), kind: 'text', config: { text: 'Sabtu, 14 Februari 2026', color: '#C5A880', fontSize: 14, align: 'center', fontFamily: 'Cormorant Garamond' } },
      { name: 'Gulir ke Bawah', ...nodeBase('front-decoration'), transform: tfm(35,88,30,6), animation: floatAnim(1200), kind: 'text', config: { text: '↓ Buka Undangan ↓', color: '#FAF8F5', fontSize: 11, align: 'center', fontFamily: 'Plus Jakarta Sans' } },
    ],
  },
  {
    id: 'cover-modern',
    sectionId: 'cover',
    name: 'Modern Minimalis',
    thumbnail: '✨',
    description: 'Cover bersih dengan tipografi bold dan foto prewedding',
    nodes: [
      { name: 'Garis Dekorasi Atas', ...nodeBase('front-decoration'), transform: tfm(25,5,50,4), animation: fadeIn(0), kind: 'text', config: { text: '— ✦ —', color: '#C5A880', fontSize: 14, align: 'center' } },
      { name: 'Label THE WEDDING OF', ...nodeBase('content'), transform: tfm(10,10,80,6), animation: fadeIn(200), kind: 'text', config: { text: 'THE WEDDING OF', color: '#88735B', fontSize: 11, align: 'center', fontFamily: 'Syncopate', letterSpacing: 3 } },
      { name: 'Nama Mempelai Wanita', ...nodeBase('content'), transform: tfm(5,17,90,14), animation: fadeIn(400), kind: 'text', config: { text: 'Raisya Putri', color: '#4A2E35', fontSize: 44, align: 'center', fontFamily: 'Playfair Display' } },
      { name: 'Simbol Dan', ...nodeBase('front-decoration'), transform: tfm(38,32,24,9), animation: fadeIn(600), kind: 'text', config: { text: '&', color: '#C5A880', fontSize: 34, align: 'center', fontFamily: 'Allura' } },
      { name: 'Nama Mempelai Pria', ...nodeBase('content'), transform: tfm(5,42,90,14), animation: fadeIn(800), kind: 'text', config: { text: 'Daffa Pratama', color: '#4A2E35', fontSize: 44, align: 'center', fontFamily: 'Playfair Display' } },
      { name: 'Foto Couple', ...nodeBase('behind-content'), transform: tfm(15,57,70,32), animation: fadeIn(500), kind: 'image', config: { src: LP, fit: 'cover' } },
      { name: 'Tanggal & Kota', ...nodeBase('content'), transform: tfm(15,91,70,6), animation: fadeIn(1000), kind: 'text', config: { text: '14 · 02 · 2026  |  Kebumen, Jawa Tengah', color: '#4A2E35', fontSize: 11, align: 'center', fontFamily: 'Plus Jakarta Sans', letterSpacing: 1 } },
    ],
  },
  {
    id: 'cover-syari',
    sectionId: 'cover',
    name: "Syar'i & Islami",
    thumbnail: '🕌',
    description: 'Cover bernuansa islami dengan kaligrafi dan ayat suci',
    nodes: [
      { name: 'Kaligrafi Bismillah', ...nodeBase('content'), transform: tfm(10,5,80,12), animation: fadeIn(0), kind: 'text', config: { text: '﷽', color: '#C5A880', fontSize: 38, align: 'center', fontFamily: 'Amiri' } },
      { name: 'Ayat Taaruf', ...nodeBase('content'), transform: tfm(10,18,80,8), animation: fadeIn(200), kind: 'text', config: { text: '"Dan di antara tanda-tanda kebesaran-Nya ialah Dia menciptakan pasangan-pasangan untukmu..."\n— QS. Ar-Rum: 21', color: '#88735B', fontSize: 11, align: 'center', fontFamily: 'EB Garamond' } },
      { name: 'Label Undangan', ...nodeBase('content'), transform: tfm(10,30,80,6), animation: fadeIn(400), kind: 'text', config: { text: 'Undangan Pernikahan', color: '#4A2E35', fontSize: 13, align: 'center', fontFamily: 'Plus Jakarta Sans', letterSpacing: 2 } },
      { name: 'Nama Couple', ...nodeBase('content'), transform: tfm(5,37,90,18), animation: fadeIn(600), kind: 'text', config: { text: 'Siti Nur Aini\n& M. Rizky Ramadhan', color: '#4A2E35', fontSize: 32, align: 'center', fontFamily: 'Cinzel' } },
      { name: 'Foto Pasangan', ...nodeBase('behind-content'), transform: tfm(25,56,50,28), animation: fadeIn(400), kind: 'image', config: { src: PP, fit: 'cover' } },
      { name: 'Tanggal Hijriah & Masehi', ...nodeBase('content'), transform: tfm(10,86,80,11), animation: fadeIn(800), kind: 'text', config: { text: 'Ahad, 20 Rajab 1447 H\n18 Januari 2026 M\nKebumen, Jawa Tengah', color: '#4A2E35', fontSize: 12, align: 'center', fontFamily: 'Lora' } },
    ],
  },
  {
    id: 'cover-botanical',
    sectionId: 'cover',
    name: 'Botanical Garden',
    thumbnail: '🌿',
    description: 'Dekorasi daun tropis dengan frame foto natural',
    nodes: [
      { name: 'Frame Foto Arch', ...nodeBase('behind-content'), transform: tfm(20,10,60,50), animation: fadeIn(200), kind: 'image', config: { src: AP, fit: 'cover' } },
      { name: 'Ornamen Daun Kiri Atas', ...nodeBase('front-decoration'), transform: tfm(0,0,28,22), animation: swayAnim(0), kind: 'text', config: { text: '🌿', color: '#88735B', fontSize: 58, align: 'left' } },
      { name: 'Ornamen Daun Kanan Atas', ...nodeBase('front-decoration'), transform: tfm(72,0,28,22), animation: swayAnim(300), kind: 'text', config: { text: '🍃', color: '#88735B', fontSize: 58, align: 'right' } },
      { name: 'Label We Are Getting Married', ...nodeBase('content'), transform: tfm(10,62,80,6), animation: fadeIn(400), kind: 'text', config: { text: 'WE ARE GETTING MARRIED', color: '#88735B', fontSize: 10, align: 'center', fontFamily: 'Syncopate', letterSpacing: 3 } },
      { name: 'Nama Couple', ...nodeBase('content'), transform: tfm(5,69,90,16), animation: fadeIn(600), kind: 'text', config: { text: 'Ananda & Bintang', color: '#4A2E35', fontSize: 42, align: 'center', fontFamily: 'Allura' } },
      { name: 'Tanggal', ...nodeBase('content'), transform: tfm(20,86,60,6), animation: fadeIn(800), kind: 'text', config: { text: '14 Februari 2026', color: '#88735B', fontSize: 13, align: 'center', fontFamily: 'Lora' } },
    ],
  },
  {
    id: 'cover-golden-arch',
    sectionId: 'cover',
    name: 'Golden Arch',
    thumbnail: '✨',
    description: 'Frame emas mewah dengan foto portrait besar',
    nodes: [
      { name: 'Ornamen Atas', ...nodeBase('front-decoration'), transform: tfm(35,2,30,6), animation: fadeIn(0), kind: 'text', config: { text: '✦ ✧ ✦', color: '#C5A880', fontSize: 20, align: 'center' } },
      { name: 'Foto Portrait Utama', ...nodeBase('behind-content'), transform: tfm(25,10,50,46), animation: fadeIn(300), kind: 'image', config: { src: PP, fit: 'cover' } },
      { name: 'Label Undangan', ...nodeBase('content'), transform: tfm(10,58,80,5), animation: fadeIn(500), kind: 'text', config: { text: 'THE WEDDING OF', color: '#88735B', fontSize: 10, align: 'center', fontFamily: 'Syncopate', letterSpacing: 4 } },
      { name: 'Nama Besar', ...nodeBase('content'), transform: tfm(5,64,90,18), animation: fadeIn(700), kind: 'text', config: { text: 'Ananda\n&\nBintang', color: '#4A2E35', fontSize: 36, align: 'center', fontFamily: 'Cinzel' } },
      { name: 'Tanggal & Tempat', ...nodeBase('content'), transform: tfm(15,83,70,8), animation: fadeIn(900), kind: 'text', config: { text: '14.02.2026\nKebumen, Jawa Tengah', color: '#88735B', fontSize: 12, align: 'center', fontFamily: 'Lora' } },
      { name: 'Ornamen Bawah', ...nodeBase('front-decoration'), transform: tfm(35,92,30,5), animation: fadeIn(1100), kind: 'text', config: { text: '—— ✦ ——', color: '#C5A880', fontSize: 14, align: 'center' } },
    ],
  },
  {
    id: 'cover-polaroid-collage',
    sectionId: 'cover',
    name: 'Polaroid Collage',
    thumbnail: '📸',
    description: 'Kumpulan foto polaroid casual dan playful',
    nodes: [
      { name: 'Foto Polaroid 1', ...nodeBase('behind-content'), transform: tfm(8,8,38,32), animation: fadeIn(100), kind: 'image', config: { src: PLP, fit: 'cover' } },
      { name: 'Foto Polaroid 2', ...nodeBase('behind-content'), transform: tfm(54,6,38,32), animation: fadeIn(300), kind: 'image', config: { src: PLP, fit: 'cover' } },
      { name: 'Foto Polaroid 3', ...nodeBase('behind-content'), transform: tfm(31,36,38,32), animation: fadeIn(500), kind: 'image', config: { src: PLP, fit: 'cover' } },
      { name: 'Label Save The Date', ...nodeBase('content'), transform: tfm(10,70,80,6), animation: fadeIn(700), kind: 'text', config: { text: 'SAVE THE DATE', color: '#4A2E35', fontSize: 11, align: 'center', fontFamily: 'Syncopate', letterSpacing: 3 } },
      { name: 'Nama Couple', ...nodeBase('content'), transform: tfm(5,77,90,12), animation: fadeIn(900), kind: 'text', config: { text: 'Ananda & Bintang', color: '#4A2E35', fontSize: 38, align: 'center', fontFamily: 'Great Vibes' } },
      { name: 'Tanggal', ...nodeBase('content'), transform: tfm(20,90,60,5), animation: fadeIn(1100), kind: 'text', config: { text: '14 Februari 2026', color: '#88735B', fontSize: 13, align: 'center', fontFamily: 'Plus Jakarta Sans' } },
    ],
  },
  {
    id: 'cover-vintage-frame',
    sectionId: 'cover',
    name: 'Vintage Frame',
    thumbnail: '🖼️',
    description: 'Bingkai vintage klasik dengan foto landscape',
    nodes: [
      { name: 'Border Ornamen Atas', ...nodeBase('front-decoration'), transform: tfm(10,5,80,8), animation: fadeIn(0), kind: 'text', config: { text: '╭─────✧❂✧─────╮', color: '#C5A880', fontSize: 14, align: 'center', fontFamily: 'monospace' } },
      { name: 'Label Invitation', ...nodeBase('content'), transform: tfm(10,14,80,5), animation: fadeIn(200), kind: 'text', config: { text: 'WEDDING INVITATION', color: '#88735B', fontSize: 9, align: 'center', fontFamily: 'Syncopate', letterSpacing: 3 } },
      { name: 'Foto Landscape', ...nodeBase('content'), transform: tfm(15,21,70,36), animation: fadeIn(400), kind: 'image', config: { src: LP, fit: 'cover' } },
      { name: 'Nama Couple', ...nodeBase('content'), transform: tfm(5,59,90,16), animation: fadeIn(600), kind: 'text', config: { text: 'Ananda Putri\n&\nBintang Pratama', color: '#4A2E35', fontSize: 28, align: 'center', fontFamily: 'Playfair Display' } },
      { name: 'Tanggal Lengkap', ...nodeBase('content'), transform: tfm(15,77,70,8), animation: fadeIn(800), kind: 'text', config: { text: 'Sabtu, 14 Februari 2026\nKebumen, Jawa Tengah', color: '#88735B', fontSize: 11, align: 'center', fontFamily: 'Lora' } },
      { name: 'Border Ornamen Bawah', ...nodeBase('front-decoration'), transform: tfm(10,87,80,8), animation: fadeIn(1000), kind: 'text', config: { text: '╰─────✧❂✧─────╯', color: '#C5A880', fontSize: 14, align: 'center', fontFamily: 'monospace' } },
    ],
  },
  {
    id: 'cover-circle-frame',
    sectionId: 'cover',
    name: 'Circle Frame',
    thumbnail: '⭕',
    description: 'Foto couple di dalam frame lingkaran elegan',
    nodes: [
      { name: 'Foto Circle', ...nodeBase('content'), transform: tfm(25,8,50,40), animation: fadeIn(300), kind: 'image', config: { src: CP, fit: 'cover' } },
      { name: 'Ornamen Ring Luar', ...nodeBase('front-decoration'), transform: tfm(35,50,30,7), animation: floatAnim(500), kind: 'text', config: { text: '◈ ◈ ◈', color: '#C5A880', fontSize: 18, align: 'center' } },
      { name: 'Label Wedding', ...nodeBase('content'), transform: tfm(10,58,80,5), animation: fadeIn(600), kind: 'text', config: { text: 'W E D D I N G', color: '#88735B', fontSize: 10, align: 'center', fontFamily: 'Syncopate', letterSpacing: 5 } },
      { name: 'Nama Couple', ...nodeBase('content'), transform: tfm(5,64,90,16), animation: fadeIn(800), kind: 'text', config: { text: 'Ananda & Bintang', color: '#4A2E35', fontSize: 44, align: 'center', fontFamily: 'Allura' } },
      { name: 'Tanggal', ...nodeBase('content'), transform: tfm(20,81,60,6), animation: fadeIn(1000), kind: 'text', config: { text: '14 • 02 • 2026', color: '#88735B', fontSize: 13, align: 'center', fontFamily: 'Plus Jakarta Sans' } },
      { name: 'Lokasi', ...nodeBase('content'), transform: tfm(20,88,60,5), animation: fadeIn(1200), kind: 'text', config: { text: 'Kebumen, Jawa Tengah', color: '#6B5E62', fontSize: 11, align: 'center', fontFamily: 'Lora' } },
    ],
  },
  {
    id: 'cover-dual-portrait',
    sectionId: 'cover',
    name: 'Dual Portrait',
    thumbnail: '👫',
    description: 'Dua foto portrait mempelai berdampingan',
    nodes: [
      { name: 'Label Atas', ...nodeBase('content'), transform: tfm(10,5,80,6), animation: fadeIn(0), kind: 'text', config: { text: 'WEDDING INVITATION', color: '#88735B', fontSize: 9, align: 'center', fontFamily: 'Syncopate', letterSpacing: 3 } },
      { name: 'Foto Mempelai Wanita', ...nodeBase('content'), transform: tfm(5,13,42,44), animation: fadeIn(300), kind: 'image', config: { src: PP, fit: 'cover' } },
      { name: 'Foto Mempelai Pria', ...nodeBase('content'), transform: tfm(53,13,42,44), animation: fadeIn(300), kind: 'image', config: { src: PP, fit: 'cover' } },
      { name: 'Divider Ampersand', ...nodeBase('front-decoration'), transform: tfm(43,31,14,14), animation: floatAnim(600), kind: 'text', config: { text: '&', color: '#C5A880', fontSize: 46, align: 'center', fontFamily: 'Allura' } },
      { name: 'Nama Couple', ...nodeBase('content'), transform: tfm(5,59,90,16), animation: fadeIn(800), kind: 'text', config: { text: 'Ananda & Bintang', color: '#4A2E35', fontSize: 42, align: 'center', fontFamily: 'Great Vibes' } },
      { name: 'Tanggal & Lokasi', ...nodeBase('content'), transform: tfm(15,76,70,10), animation: fadeIn(1000), kind: 'text', config: { text: 'Sabtu, 14 Februari 2026\nKebumen, Jawa Tengah', color: '#88735B', fontSize: 12, align: 'center', fontFamily: 'Lora' } },
      { name: 'CTA Scroll', ...nodeBase('front-decoration'), transform: tfm(30,88,40,6), animation: floatAnim(1200), kind: 'text', config: { text: '↓ Buka Undangan ↓', color: '#C5A880', fontSize: 11, align: 'center', fontFamily: 'Plus Jakarta Sans' } },
    ],
  },
  {
    id: 'cover-venue-hero',
    sectionId: 'cover',
    name: 'Venue Hero',
    thumbnail: '🏛️',
    description: 'Foto venue/gedung sebagai latar dramatis',
    nodes: [
      { name: 'Foto Venue Background', ...nodeBase('background'), transform: tfm(0,0,100,100), animation: staticAnim(), kind: 'image', config: { src: VP, fit: 'cover' } },
      { name: 'Label Join Us', ...nodeBase('content'), transform: tfm(10,35,80,6), animation: fadeIn(200), kind: 'text', config: { text: 'YOU ARE INVITED TO JOIN US', color: '#C5A880', fontSize: 10, align: 'center', fontFamily: 'Syncopate', letterSpacing: 2 } },
      { name: 'Nama Couple', ...nodeBase('content'), transform: tfm(5,42,90,20), animation: fadeIn(500), kind: 'text', config: { text: 'Ananda\n&\nBintang', color: '#FAF8F5', fontSize: 46, align: 'center', fontFamily: 'Cinzel' } },
      { name: 'Garis Pembatas', ...nodeBase('front-decoration'), transform: tfm(30,63,40,4), animation: fadeIn(700), kind: 'text', config: { text: '━━━ ✦ ━━━', color: '#C5A880', fontSize: 14, align: 'center' } },
      { name: 'Tanggal', ...nodeBase('content'), transform: tfm(15,68,70,7), animation: fadeIn(900), kind: 'text', config: { text: 'Sabtu, 14 Februari 2026', color: '#FAF8F5', fontSize: 15, align: 'center', fontFamily: 'Cormorant Garamond' } },
      { name: 'Lokasi Venue', ...nodeBase('content'), transform: tfm(20,76,60,6), animation: fadeIn(1100), kind: 'text', config: { text: 'Gedung Graha Kebumen', color: '#C5A880', fontSize: 13, align: 'center', fontFamily: 'Plus Jakarta Sans' } },
    ],
  },
];
