import { TemplateThemePreset } from "./types";

export const TEMPLATES_CATALOG: TemplateThemePreset[] = [
  // ==========================================
  // 1. BOTANICAL (8 Presets)
  // ==========================================
  {
    id: "autumnelle",
    title: "Autumnelle Garden",
    sourceOrigin: "HelloGuest",
    archetypeId: "botanical",
    category: "Botanical Floral",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#5C6F57",
      secondary: "#8A9A86",
      accent: "#B85D3B",
      background: "#FAF7F5",
      text: "#261F23",
      cardBg: "#FFFFFF",
      border: "#E2E8E0",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloralWreath", exitAnimId: "page-turn", entryAnimId: "fall-in", bgVariant: "light-cream-watercolor" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "boarding-pass", mapStyle: "interactive-clean", storiesStyle: "filmstrip-scroll", galleryStyle: "masonry-staggered", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "tulivelle",
    title: "Tulivelle Blossom",
    sourceOrigin: "HelloGuest",
    archetypeId: "botanical",
    category: "Botanical Floral",
    previewImageUrl: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=600",
    colors: {
      primary: "#7A8C74",
      secondary: "#A3B39E",
      accent: "#D48B72",
      background: "#FCFAF8",
      text: "#2B2428",
      cardBg: "#FFFFFF",
      border: "#E8EFE6",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "floral-watercolor",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloralWreath", exitAnimId: "curtain-reveal", entryAnimId: "rise-up", bgVariant: "soft-pink-blush" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "vertical-timeline", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "polaroid-scatter", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "poetic-photo-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "fiorella",
    title: "Fiorella Spring",
    sourceOrigin: "UndanganDigital",
    archetypeId: "botanical",
    category: "Botanical Floral",
    previewImageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=600",
    colors: {
      primary: "#6B8E23",
      secondary: "#9ACD32",
      accent: "#E9967A",
      background: "#F9FBF7",
      text: "#222620",
      cardBg: "#FFFFFF",
      border: "#E4EDE0",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "floral-watercolor",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloatingCard", exitAnimId: "scroll-roll", entryAnimId: "scale-in", bgVariant: "fresh-green-mist" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "calendar-grid", mapStyle: "minimalist-guide", storiesStyle: "milestone-cards", galleryStyle: "film-roll-carousel", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "cute-waving-outro", sfxTheme: "gentle-nature" },
  },
  {
    id: "serenade-green",
    title: "Serenade Olive",
    sourceOrigin: "HelloGuest",
    archetypeId: "botanical",
    category: "Botanical Floral",
    previewImageUrl: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=600",
    colors: {
      primary: "#384938",
      secondary: "#5E735E",
      accent: "#CCA873",
      background: "#F6F7F5",
      text: "#1E261E",
      cardBg: "#FFFFFF",
      border: "#D8E0D7",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloatingCard", exitAnimId: "fade-drop", entryAnimId: "fade-in", bgVariant: "sage-wash" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "twin-arch-gate", mapStyle: "interactive-clean", storiesStyle: "magazine-article", galleryStyle: "mosaic-hero", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "serenade-rose",
    title: "Serenade Dusty Rose",
    sourceOrigin: "HelloGuest",
    archetypeId: "botanical",
    category: "Botanical Floral",
    previewImageUrl: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?q=80&w=600",
    colors: {
      primary: "#7D424D",
      secondary: "#A66D77",
      accent: "#D4A89C",
      background: "#FAF6F6",
      text: "#28171B",
      cardBg: "#FFFFFF",
      border: "#EDE0E2",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "floral-watercolor",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloralWreath", exitAnimId: "flip-3d", entryAnimId: "rotate-in", bgVariant: "dusty-rose" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "boarding-pass", mapStyle: "illustrated-cute", storiesStyle: "filmstrip-scroll", galleryStyle: "polaroid-scatter", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "poetic-photo-outro", sfxTheme: "gentle-nature" },
  },
  {
    id: "serenade-moss",
    title: "Serenade Deep Moss",
    sourceOrigin: "UndanganDigital",
    archetypeId: "botanical",
    category: "Botanical Floral",
    previewImageUrl: "https://images.unsplash.com/photo-1509927083803-4bd519298ac4?q=80&w=600",
    colors: {
      primary: "#2D4030",
      secondary: "#4C6B52",
      accent: "#C2A670",
      background: "#F5F7F4",
      text: "#1A241C",
      cardBg: "#FFFFFF",
      border: "#D2DED4",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloatingCard", exitAnimId: "zoom-away", entryAnimId: "rise-up", bgVariant: "deep-moss" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "vertical-timeline", mapStyle: "minimalist-guide", storiesStyle: "chat-journey", galleryStyle: "masonry-staggered", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "cute-waving-outro", sfxTheme: "gentle-nature" },
  },
  {
    id: "celestine",
    title: "Celestine Botanical",
    sourceOrigin: "HelloGuest",
    archetypeId: "botanical",
    category: "Botanical Floral",
    previewImageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=600",
    colors: {
      primary: "#4F6354",
      secondary: "#7A9180",
      accent: "#E29578",
      background: "#FAF9F6",
      text: "#222B24",
      cardBg: "#FFFFFF",
      border: "#E1EAE3",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloralWreath", exitAnimId: "slide-down", entryAnimId: "unfurl", bgVariant: "sage-terracotta" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "calendar-grid", mapStyle: "interactive-clean", storiesStyle: "milestone-cards", galleryStyle: "film-roll-carousel", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "botanica-terracotta",
    title: "Botanica Terracotta",
    sourceOrigin: "HariKita Original",
    archetypeId: "botanical",
    category: "Botanical Floral",
    previewImageUrl: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?q=80&w=600",
    colors: {
      primary: "#A35038",
      secondary: "#C47762",
      accent: "#566D57",
      background: "#FDF8F5",
      text: "#331E18",
      cardBg: "#FFFFFF",
      border: "#EEDCD6",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloatingCard", exitAnimId: "gate-open", entryAnimId: "doors-close", bgVariant: "warm-earth" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "twin-arch-gate", mapStyle: "illustrated-cute", storiesStyle: "magazine-article", galleryStyle: "mosaic-hero", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "poetic-photo-outro", sfxTheme: "gentle-nature" },
  },

  // ==========================================
  // 2. JAVANESE (8 Presets)
  // ==========================================
  {
    id: "javanese-royal",
    title: "Javanese Royal Keraton",
    sourceOrigin: "HariKita Original",
    archetypeId: "javanese",
    category: "Cultural Adat",
    previewImageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=600",
    colors: {
      primary: "#CCA873",
      secondary: "#E0C89E",
      accent: "#B85D3B",
      background: "#1E120D",
      text: "#F5ECD7",
      cardBg: "#2B1B14",
      border: "#6E4C33",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "batik-wayang",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "GateDoors", exitAnimId: "gate-open", entryAnimId: "doors-close", bgVariant: "dark-mahogany-gold" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "twin-arch-gate", mapStyle: "minimalist-guide", storiesStyle: "magazine-article", galleryStyle: "masonry-staggered", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "royal-gamelan" },
  },
  {
    id: "javanese-azurite",
    title: "Javanese Royal Azurite",
    sourceOrigin: "HariKita Original",
    archetypeId: "javanese",
    category: "Cultural Adat",
    previewImageUrl: "https://images.unsplash.com/photo-1529636798458-92182e662485?q=80&w=600",
    colors: {
      primary: "#CBA469",
      secondary: "#334E68",
      accent: "#E2C38B",
      background: "#101A24",
      text: "#F0F4F8",
      cardBg: "#182635",
      border: "#486581",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "batik-wayang",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "ScrollUnroll", exitAnimId: "scroll-roll", entryAnimId: "unfurl", bgVariant: "deep-indigo-blue" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "boarding-pass", mapStyle: "interactive-clean", storiesStyle: "filmstrip-scroll", galleryStyle: "film-roll-carousel", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "royal-gamelan" },
  },
  {
    id: "javanese-umber",
    title: "Javanese Teak Umber",
    sourceOrigin: "UndanganDigital",
    archetypeId: "javanese",
    category: "Cultural Adat",
    previewImageUrl: "https://images.unsplash.com/photo-1544078741-7fe023cb4458?q=80&w=600",
    colors: {
      primary: "#D4AF37",
      secondary: "#8B5A2B",
      accent: "#C68E17",
      background: "#1C120C",
      text: "#FAF0E6",
      cardBg: "#2A1D15",
      border: "#5E402B",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "batik-wayang",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "GateDoors", exitAnimId: "curtain-reveal", entryAnimId: "fall-in", bgVariant: "dark-teak-brown" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "vertical-timeline", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "mosaic-hero", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "royal-gamelan" },
  },
  {
    id: "javanese-ivory",
    title: "Javanese Ivory Prada",
    sourceOrigin: "HelloGuest",
    archetypeId: "javanese",
    category: "Cultural Adat",
    previewImageUrl: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=600",
    colors: {
      primary: "#8B6508",
      secondary: "#CD950C",
      accent: "#B8860B",
      background: "#FBF8F2",
      text: "#2B2118",
      cardBg: "#FFFFFF",
      border: "#E6DBC9",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "batik-wayang",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "ScrollUnroll", exitAnimId: "page-turn", entryAnimId: "scale-in", bgVariant: "ivory-cream-light" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "calendar-grid", mapStyle: "minimalist-guide", storiesStyle: "milestone-cards", galleryStyle: "polaroid-scatter", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "royal-gamelan" },
  },
  {
    id: "javanese-crimson",
    title: "Javanese Crimson Palace",
    sourceOrigin: "HariKita Original",
    archetypeId: "javanese",
    category: "Cultural Adat",
    previewImageUrl: "https://images.unsplash.com/photo-1509927083803-4bd519298ac4?q=80&w=600",
    colors: {
      primary: "#CCA873",
      secondary: "#7A1C25",
      accent: "#F0D39B",
      background: "#240B0E",
      text: "#FDF4E7",
      cardBg: "#351217",
      border: "#7A2E36",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "batik-wayang",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "GateDoors", exitAnimId: "flip-3d", entryAnimId: "rotate-in", bgVariant: "deep-crimson-dark" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "twin-arch-gate", mapStyle: "interactive-clean", storiesStyle: "magazine-article", galleryStyle: "masonry-staggered", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "royal-gamelan" },
  },
  {
    id: "javanese-golden",
    title: "Javanese Golden Garuda",
    sourceOrigin: "UndanganDigital",
    archetypeId: "javanese",
    category: "Cultural Adat",
    previewImageUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=600",
    colors: {
      primary: "#D4AF37",
      secondary: "#A67C1E",
      accent: "#FFDF73",
      background: "#17140B",
      text: "#FFF9E6",
      cardBg: "#292415",
      border: "#6E5E2E",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "batik-wayang",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "ScrollUnroll", exitAnimId: "zoom-away", entryAnimId: "rise-up", bgVariant: "deep-gold-galaxy" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "boarding-pass", mapStyle: "illustrated-cute", storiesStyle: "filmstrip-scroll", galleryStyle: "film-roll-carousel", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "royal-gamelan" },
  },
  {
    id: "javanese-kebumen",
    title: "Javanese Kebumen Heritage",
    sourceOrigin: "HariKita Original",
    archetypeId: "javanese",
    category: "Cultural Adat",
    previewImageUrl: "https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=600",
    colors: {
      primary: "#B8860B",
      secondary: "#4E3629",
      accent: "#E5C158",
      background: "#211611",
      text: "#FAF4E8",
      cardBg: "#31221B",
      border: "#73503B",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "batik-wayang",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "GateDoors", exitAnimId: "fade-drop", entryAnimId: "fade-in", bgVariant: "warm-kebumen-earth" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "vertical-timeline", mapStyle: "minimalist-guide", storiesStyle: "chat-journey", galleryStyle: "mosaic-hero", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "royal-gamelan" },
  },
  {
    id: "javanese-pearl",
    title: "Javanese White Pearl",
    sourceOrigin: "HelloGuest",
    archetypeId: "javanese",
    category: "Cultural Adat",
    previewImageUrl: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=600",
    colors: {
      primary: "#9C7A3C",
      secondary: "#D4AF37",
      accent: "#5C4033",
      background: "#FAF7F2",
      text: "#261D15",
      cardBg: "#FFFFFF",
      border: "#E6DBCB",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "batik-wayang",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "ScrollUnroll", exitAnimId: "slide-up", entryAnimId: "slide-left", bgVariant: "pearl-ivory-light" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "calendar-grid", mapStyle: "interactive-clean", storiesStyle: "milestone-cards", galleryStyle: "polaroid-scatter", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "royal-gamelan" },
  },

  // ==========================================
  // 3. ISLAMIC (8 Presets)
  // ==========================================
  {
    id: "medina-gold",
    title: "Medina Royal Gold",
    sourceOrigin: "HariKita Original",
    archetypeId: "islamic",
    category: "Syar'i Islamic",
    previewImageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=600",
    colors: {
      primary: "#0D382B",
      secondary: "#1E5A47",
      accent: "#CCA873",
      background: "#F6F8F6",
      text: "#1B2822",
      cardBg: "#FFFFFF",
      border: "#D6E4DC",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "arabic-arch",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "IslamicArch", exitAnimId: "scroll-roll", entryAnimId: "rise-up", bgVariant: "clean-white-emerald" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "twin-arch-gate", mapStyle: "interactive-clean", storiesStyle: "magazine-article", galleryStyle: "masonry-staggered", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "emerald-syari",
    title: "Emerald Syar'i Grace",
    sourceOrigin: "UndanganDigital",
    archetypeId: "islamic",
    category: "Syar'i Islamic",
    previewImageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=600",
    colors: {
      primary: "#0A4032",
      secondary: "#1B6350",
      accent: "#D4AF37",
      background: "#F4FAF7",
      text: "#142922",
      cardBg: "#FFFFFF",
      border: "#CDE5DC",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "arabic-arch",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "IslamicArch", exitAnimId: "curtain-reveal", entryAnimId: "fall-in", bgVariant: "deep-emerald" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "minimalist-guide", storiesStyle: "filmstrip-scroll", galleryStyle: "film-roll-carousel", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "walimatul-ursy",
    title: "Walimatul 'Ursy Classic",
    sourceOrigin: "HelloGuest",
    archetypeId: "islamic",
    category: "Syar'i Islamic",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#143D30",
      secondary: "#235C4A",
      accent: "#C69B56",
      background: "#FAF7F2",
      text: "#202E27",
      cardBg: "#FFFFFF",
      border: "#E2DDD3",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "arabic-arch",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "IslamicArch", exitAnimId: "fade-drop", entryAnimId: "fade-in", bgVariant: "classic-green-ivory" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "vertical-timeline", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "mosaic-hero", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "al-fatih",
    title: "Al-Fatih Heritage",
    sourceOrigin: "HariKita Original",
    archetypeId: "islamic",
    category: "Syar'i Islamic",
    previewImageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=600",
    colors: {
      primary: "#16382E",
      secondary: "#2D5C4E",
      accent: "#D9B464",
      background: "#F8FAF8",
      text: "#1D2B26",
      cardBg: "#FFFFFF",
      border: "#D5E3DC",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "arabic-arch",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "IslamicArch", exitAnimId: "flip-3d", entryAnimId: "scale-in", bgVariant: "heritage-green" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "calendar-grid", mapStyle: "interactive-clean", storiesStyle: "milestone-cards", galleryStyle: "polaroid-scatter", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "salsabila",
    title: "Salsabila Spring",
    sourceOrigin: "UndanganDigital",
    archetypeId: "islamic",
    category: "Syar'i Islamic",
    previewImageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=600",
    colors: {
      primary: "#1A4739",
      secondary: "#35705D",
      accent: "#E2C37A",
      background: "#F5FBF8",
      text: "#1B2E27",
      cardBg: "#FFFFFF",
      border: "#CFE8DE",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "arabic-arch",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "IslamicArch", exitAnimId: "page-turn", entryAnimId: "unfurl", bgVariant: "spring-emerald" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "twin-arch-gate", mapStyle: "minimalist-guide", storiesStyle: "magazine-article", galleryStyle: "masonry-staggered", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "ar-rahman",
    title: "Ar-Rahman Blessings",
    sourceOrigin: "HelloGuest",
    archetypeId: "islamic",
    category: "Syar'i Islamic",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#103328",
      secondary: "#245242",
      accent: "#C5A059",
      background: "#FDFBF7",
      text: "#1F2B26",
      cardBg: "#FFFFFF",
      border: "#DFD9CD",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "arabic-arch",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "IslamicArch", exitAnimId: "slide-down", entryAnimId: "rotate-in", bgVariant: "sacred-green" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "interactive-clean", storiesStyle: "filmstrip-scroll", galleryStyle: "film-roll-carousel", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "nur-jannah",
    title: "Nur Jannah Light",
    sourceOrigin: "HariKita Original",
    archetypeId: "islamic",
    category: "Syar'i Islamic",
    previewImageUrl: "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=600",
    colors: {
      primary: "#1D4236",
      secondary: "#3A6E5C",
      accent: "#E8C87A",
      background: "#FAFDFB",
      text: "#1B2A24",
      cardBg: "#FFFFFF",
      border: "#DCEAE2",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "arabic-arch",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "IslamicArch", exitAnimId: "gate-open", entryAnimId: "doors-close", bgVariant: "light-paradise" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "vertical-timeline", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "mosaic-hero", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "barakah-rose",
    title: "Barakah Rose Gold",
    sourceOrigin: "UndanganDigital",
    archetypeId: "islamic",
    category: "Syar'i Islamic",
    previewImageUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?q=80&w=600",
    colors: {
      primary: "#2E3B33",
      secondary: "#4F6357",
      accent: "#D4A89C",
      background: "#FAF6F5",
      text: "#2B2423",
      cardBg: "#FFFFFF",
      border: "#E8DEDC",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "arabic-arch",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "IslamicArch", exitAnimId: "zoom-away", entryAnimId: "slide-left", bgVariant: "rose-green-blend" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "calendar-grid", mapStyle: "minimalist-guide", storiesStyle: "milestone-cards", galleryStyle: "polaroid-scatter", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "romantic-harp" },
  },

  // ==========================================
  // 4. MINIMALIST (8 Presets)
  // ==========================================
  {
    id: "seraphicus",
    title: "Seraphicus Vogue",
    sourceOrigin: "HelloGuest",
    archetypeId: "minimalist",
    category: "Minimalist Editorial",
    previewImageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600",
    colors: {
      primary: "#171717",
      secondary: "#404040",
      accent: "#737373",
      background: "#FFFFFF",
      text: "#0A0A0A",
      cardBg: "#FAFAFA",
      border: "#E5E5E5",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "minimal-line",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FullBleedText", exitAnimId: "slide-up", entryAnimId: "rise-up", bgVariant: "pure-white" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "minimalist-guide", storiesStyle: "magazine-article", galleryStyle: "masonry-staggered", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "wax-seal-signature", sfxTheme: "modern-pop" },
  },
  {
    id: "minimal-noir",
    title: "Minimal Noir Haute",
    sourceOrigin: "UndanganDigital",
    archetypeId: "minimalist",
    category: "Minimalist Editorial",
    previewImageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600",
    colors: {
      primary: "#000000",
      secondary: "#262626",
      accent: "#525252",
      background: "#FFFFFF",
      text: "#0A0A0A",
      cardBg: "#F5F5F5",
      border: "#D4D4D4",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "minimal-line",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "SplitPanelHorizontal", exitAnimId: "flip-3d", entryAnimId: "scale-in", bgVariant: "stark-white-black" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "vertical-timeline", mapStyle: "interactive-clean", storiesStyle: "filmstrip-scroll", galleryStyle: "film-roll-carousel", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "celestial-odyssey",
    title: "Kinfolk Odyssey",
    sourceOrigin: "HelloGuest",
    archetypeId: "minimalist",
    category: "Minimalist Editorial",
    previewImageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=600",
    colors: {
      primary: "#262626",
      secondary: "#525252",
      accent: "#A3A3A3",
      background: "#FAFAFA",
      text: "#171717",
      cardBg: "#FFFFFF",
      border: "#E5E5E5",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "minimal-line",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FullBleedText", exitAnimId: "fade-drop", entryAnimId: "fade-in", bgVariant: "off-white" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "calendar-grid", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "polaroid-scatter", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "cute-waving-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "blanc-studio",
    title: "Blanc Studio Pure",
    sourceOrigin: "HariKita Original",
    archetypeId: "minimalist",
    category: "Minimalist Editorial",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#1A1A1A",
      secondary: "#4A4A4A",
      accent: "#8C8C8C",
      background: "#FFFFFF",
      text: "#141414",
      cardBg: "#F8F8F8",
      border: "#EEEEEE",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "minimal-line",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "BookCover", exitAnimId: "page-turn", entryAnimId: "unfurl", bgVariant: "studio-white" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "minimalist-guide", storiesStyle: "milestone-cards", galleryStyle: "masonry-staggered", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "wax-seal-signature", sfxTheme: "modern-pop" },
  },
  {
    id: "harmony-gray",
    title: "Harmony Gray Architecture",
    sourceOrigin: "UndanganDigital",
    archetypeId: "minimalist",
    category: "Minimalist Editorial",
    previewImageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600",
    colors: {
      primary: "#333333",
      secondary: "#666666",
      accent: "#999999",
      background: "#F9F9F9",
      text: "#1C1C1C",
      cardBg: "#FFFFFF",
      border: "#E0E0E0",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "minimal-line",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "SplitPanelHorizontal", exitAnimId: "curtain-reveal", entryAnimId: "fall-in", bgVariant: "warm-gray" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "vertical-timeline", mapStyle: "interactive-clean", storiesStyle: "magazine-article", galleryStyle: "film-roll-carousel", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "clay-peak",
    title: "Clay Peak Modernist",
    sourceOrigin: "HelloGuest",
    archetypeId: "minimalist",
    category: "Minimalist Editorial",
    previewImageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600",
    colors: {
      primary: "#3D3430",
      secondary: "#6E625D",
      accent: "#B0A39C",
      background: "#FBF9F8",
      text: "#241E1B",
      cardBg: "#FFFFFF",
      border: "#E8E1DE",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "minimal-line",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FullBleedText", exitAnimId: "zoom-away", entryAnimId: "rotate-in", bgVariant: "clay-cream" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "calendar-grid", mapStyle: "illustrated-cute", storiesStyle: "filmstrip-scroll", galleryStyle: "mosaic-hero", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "cute-waving-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "marble-mist",
    title: "Marble Mist Gallery",
    sourceOrigin: "HariKita Original",
    archetypeId: "minimalist",
    category: "Minimalist Editorial",
    previewImageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=600",
    colors: {
      primary: "#2C3539",
      secondary: "#5B686E",
      accent: "#9CA8AE",
      background: "#F7F9FA",
      text: "#1E2427",
      cardBg: "#FFFFFF",
      border: "#DFE5E8",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "minimal-line",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "SplitPanelHorizontal", exitAnimId: "scroll-roll", entryAnimId: "slide-left", bgVariant: "marble-off-white" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "twin-arch-gate", mapStyle: "minimalist-guide", storiesStyle: "chat-journey", galleryStyle: "polaroid-scatter", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "wax-seal-signature", sfxTheme: "modern-pop" },
  },
  {
    id: "serenity-sky",
    title: "Serenity Sky Editorial",
    sourceOrigin: "UndanganDigital",
    archetypeId: "minimalist",
    category: "Minimalist Editorial",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#2C3E50",
      secondary: "#4A6B82",
      accent: "#8FAEC4",
      background: "#F8FAFB",
      text: "#1B2631",
      cardBg: "#FFFFFF",
      border: "#DEE5EC",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "minimal-line",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "BookCover", exitAnimId: "slide-down", entryAnimId: "doors-close", bgVariant: "sky-blue-tint" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "boarding-pass", mapStyle: "interactive-clean", storiesStyle: "milestone-cards", galleryStyle: "masonry-staggered", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },

  // ==========================================
  // 5. ROSE GOLD (8 Presets)
  // ==========================================
  {
    id: "rose-gold",
    title: "Rose Gold Elegance",
    sourceOrigin: "HariKita Original",
    archetypeId: "rose-gold",
    category: "Royal Luxury",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#E0A899",
      secondary: "#CCA873",
      accent: "#D4A89C",
      background: "#201017",
      text: "#FFF0F3",
      cardBg: "#331925",
      border: "#5E3245",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "gold-foil",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "dissolve-particles", entryAnimId: "scale-in", bgVariant: "deep-maroon" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "twin-arch-gate", mapStyle: "minimalist-guide", storiesStyle: "magazine-article", galleryStyle: "mosaic-hero", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "glamour-grey",
    title: "Glamour Grey Foil",
    sourceOrigin: "UndanganDigital",
    archetypeId: "rose-gold",
    category: "Royal Luxury",
    previewImageUrl: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?q=80&w=600",
    colors: {
      primary: "#D4AF37",
      secondary: "#E8C868",
      accent: "#E0A899",
      background: "#18181B",
      text: "#FAF4F6",
      cardBg: "#27272A",
      border: "#52525B",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "gold-foil",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "zoom-away", entryAnimId: "rise-up", bgVariant: "dark-charcoal" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "boarding-pass", mapStyle: "interactive-clean", storiesStyle: "filmstrip-scroll", galleryStyle: "film-roll-carousel", giftStyle: "angpao-envelope", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "black-diamond",
    title: "Black Diamond Luxury",
    sourceOrigin: "HelloGuest",
    archetypeId: "rose-gold",
    category: "Royal Luxury",
    previewImageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=600",
    colors: {
      primary: "#D4A89C",
      secondary: "#CCA873",
      accent: "#FFDFD6",
      background: "#110D10",
      text: "#FFF4F7",
      cardBg: "#1F171D",
      border: "#473543",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "gold-foil",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "SplitPanelHorizontal", exitAnimId: "flip-3d", entryAnimId: "rotate-in", bgVariant: "pure-black" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "vertical-timeline", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "polaroid-scatter", giftStyle: "clean-pills", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "burgundy-bliss",
    title: "Burgundy Velvet Bliss",
    sourceOrigin: "HariKita Original",
    archetypeId: "rose-gold",
    category: "Royal Luxury",
    previewImageUrl: "https://images.unsplash.com/photo-1509927083803-4bd519298ac4?q=80&w=600",
    colors: {
      primary: "#CCA873",
      secondary: "#E0C28E",
      accent: "#D48598",
      background: "#240A12",
      text: "#FFF2F5",
      cardBg: "#3B111E",
      border: "#73243C",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "gold-foil",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "curtain-reveal", entryAnimId: "fall-in", bgVariant: "burgundy-velvet" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "calendar-grid", mapStyle: "minimalist-guide", storiesStyle: "milestone-cards", galleryStyle: "masonry-staggered", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "golden-seafoam",
    title: "Golden Seafoam Emerald",
    sourceOrigin: "UndanganDigital",
    archetypeId: "rose-gold",
    category: "Royal Luxury",
    previewImageUrl: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=600",
    colors: {
      primary: "#CCA873",
      secondary: "#D4AF37",
      accent: "#8EC5B6",
      background: "#0D1F1B",
      text: "#F0FAF7",
      cardBg: "#162E28",
      border: "#2F594F",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "gold-foil",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "gate-open", entryAnimId: "doors-close", bgVariant: "dark-teal" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "twin-arch-gate", mapStyle: "interactive-clean", storiesStyle: "magazine-article", galleryStyle: "mosaic-hero", giftStyle: "angpao-envelope", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "amber-grace",
    title: "Amber Grace Lustre",
    sourceOrigin: "HelloGuest",
    archetypeId: "rose-gold",
    category: "Royal Luxury",
    previewImageUrl: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=600",
    colors: {
      primary: "#E09C62",
      secondary: "#F2B885",
      accent: "#D4A89C",
      background: "#21150F",
      text: "#FFF6F0",
      cardBg: "#332219",
      border: "#6E4936",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "gold-foil",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "SplitPanelHorizontal", exitAnimId: "page-turn", entryAnimId: "unfurl", bgVariant: "amber-dark" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "illustrated-cute", storiesStyle: "filmstrip-scroll", galleryStyle: "film-roll-carousel", giftStyle: "clean-pills", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "romantic-harp" },
  },
  {
    id: "blue-sapphire",
    title: "Blue Sapphire Royalty",
    sourceOrigin: "HariKita Original",
    archetypeId: "rose-gold",
    category: "Royal Luxury",
    previewImageUrl: "https://images.unsplash.com/photo-1529636798458-92182e662485?q=80&w=600",
    colors: {
      primary: "#CCA873",
      secondary: "#DDBE8D",
      accent: "#82AFFF",
      background: "#0A1224",
      text: "#F0F5FF",
      cardBg: "#121E38",
      border: "#293D6B",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "gold-foil",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "fade-drop", entryAnimId: "fade-in", bgVariant: "deep-navy" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "vertical-timeline", mapStyle: "minimalist-guide", storiesStyle: "chat-journey", galleryStyle: "polaroid-scatter", giftStyle: "embossed-cards", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "romantic-harp" },
  },
  {
    id: "gilded-cameo",
    title: "Gilded Cameo Emblem",
    sourceOrigin: "UndanganDigital",
    archetypeId: "rose-gold",
    category: "Royal Luxury",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#D4A89C",
      secondary: "#CCA873",
      accent: "#FBE2DC",
      background: "#1C1417",
      text: "#FFF7F8",
      cardBg: "#2B1E22",
      border: "#593F47",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "gold-foil",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "SplitPanelHorizontal", exitAnimId: "scroll-roll", entryAnimId: "slide-left", bgVariant: "dark-maroon-rose" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "calendar-grid", mapStyle: "interactive-clean", storiesStyle: "milestone-cards", galleryStyle: "masonry-staggered", giftStyle: "angpao-envelope", guestbookStyle: "luxury-scrollbook", closingStyle: "poetic-photo-outro", sfxTheme: "romantic-harp" },
  },

  // ==========================================
  // 6. RUSTIC (8 Presets)
  // ==========================================
  {
    id: "cocoa-rustic",
    title: "Cocoa Rustic Pampas",
    sourceOrigin: "HelloGuest",
    archetypeId: "rustic",
    category: "Rustic Vintage",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#8C533E",
      secondary: "#B0715B",
      accent: "#D99B82",
      background: "#F7F2EA",
      text: "#2B1A14",
      cardBg: "#FFFFFF",
      border: "#E2D7C8",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "PostageStamp", exitAnimId: "page-turn", entryAnimId: "unfurl", bgVariant: "warm-linen" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "vertical-timeline", mapStyle: "illustrated-cute", storiesStyle: "filmstrip-scroll", galleryStyle: "polaroid-scatter", giftStyle: "embossed-cards", guestbookStyle: "sticky-notes", closingStyle: "poetic-photo-outro", sfxTheme: "gentle-nature" },
  },
  {
    id: "terracotta-sienna",
    title: "Terracotta Sienna Hearth",
    sourceOrigin: "HariKita Original",
    archetypeId: "rustic",
    category: "Rustic Vintage",
    previewImageUrl: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?q=80&w=600",
    colors: {
      primary: "#A0522D",
      secondary: "#CD853F",
      accent: "#DEB887",
      background: "#FAF4EE",
      text: "#2E1609",
      cardBg: "#FFFFFF",
      border: "#EADCCE",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloatingCard", exitAnimId: "slide-down", entryAnimId: "fall-in", bgVariant: "terracotta-cream" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "minimalist-guide", storiesStyle: "chat-journey", galleryStyle: "masonry-staggered", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "wax-seal-signature", sfxTheme: "gentle-nature" },
  },
  {
    id: "bohemian-bliss",
    title: "Bohemian Dried Leaves",
    sourceOrigin: "UndanganDigital",
    archetypeId: "rustic",
    category: "Rustic Vintage",
    previewImageUrl: "https://images.unsplash.com/photo-1509927083803-4bd519298ac4?q=80&w=600",
    colors: {
      primary: "#9C6644",
      secondary: "#B08968",
      accent: "#DDB892",
      background: "#F5EBE0",
      text: "#261912",
      cardBg: "#FFFFFF",
      border: "#DECABA",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "PostageStamp", exitAnimId: "curtain-reveal", entryAnimId: "slide-left", bgVariant: "pampas-beige" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "calendar-grid", mapStyle: "interactive-clean", storiesStyle: "milestone-cards", galleryStyle: "film-roll-carousel", giftStyle: "angpao-envelope", guestbookStyle: "luxury-scrollbook", closingStyle: "cute-waving-outro", sfxTheme: "gentle-nature" },
  },
  {
    id: "sienna-earth",
    title: "Sienna Earth Postal",
    sourceOrigin: "HelloGuest",
    archetypeId: "rustic",
    category: "Rustic Vintage",
    previewImageUrl: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=600",
    colors: {
      primary: "#8B4513",
      secondary: "#A0522D",
      accent: "#D2B48C",
      background: "#FAF5EF",
      text: "#261305",
      cardBg: "#FFFFFF",
      border: "#E8DACB",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloatingCard", exitAnimId: "scroll-roll", entryAnimId: "rise-up", bgVariant: "earth-beige" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "twin-arch-gate", mapStyle: "illustrated-cute", storiesStyle: "magazine-article", galleryStyle: "mosaic-hero", giftStyle: "embossed-cards", guestbookStyle: "sticky-notes", closingStyle: "wax-seal-signature", sfxTheme: "gentle-nature" },
  },
  {
    id: "golden-amber",
    title: "Golden Amber Kraft",
    sourceOrigin: "HariKita Original",
    archetypeId: "rustic",
    category: "Rustic Vintage",
    previewImageUrl: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?q=80&w=600",
    colors: {
      primary: "#B87333",
      secondary: "#CC8E52",
      accent: "#E6B88A",
      background: "#FDF9F3",
      text: "#2E1C0C",
      cardBg: "#FFFFFF",
      border: "#EBDAC5",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "PostageStamp", exitAnimId: "fade-drop", entryAnimId: "scale-in", bgVariant: "amber-kraft" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "vertical-timeline", mapStyle: "minimalist-guide", storiesStyle: "filmstrip-scroll", galleryStyle: "polaroid-scatter", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "gentle-nature" },
  },
  {
    id: "celadon-charm",
    title: "Celadon Dried Charm",
    sourceOrigin: "UndanganDigital",
    archetypeId: "rustic",
    category: "Rustic Vintage",
    previewImageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=600",
    colors: {
      primary: "#707A65",
      secondary: "#8F9A83",
      accent: "#C49A76",
      background: "#F8F7F4",
      text: "#22261E",
      cardBg: "#FFFFFF",
      border: "#DFE2DA",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloatingCard", exitAnimId: "flip-3d", entryAnimId: "rotate-in", bgVariant: "sage-celadon" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "interactive-clean", storiesStyle: "chat-journey", galleryStyle: "masonry-staggered", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "cute-waving-outro", sfxTheme: "gentle-nature" },
  },
  {
    id: "dusty-blush",
    title: "Dusty Blush Linen",
    sourceOrigin: "HelloGuest",
    archetypeId: "rustic",
    category: "Rustic Vintage",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#96656C",
      secondary: "#B5848B",
      accent: "#D9B4B9",
      background: "#FAF5F6",
      text: "#2E1C1E",
      cardBg: "#FFFFFF",
      border: "#EBDADC",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "PostageStamp", exitAnimId: "zoom-away", entryAnimId: "doors-close", bgVariant: "dusty-blush" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "calendar-grid", mapStyle: "illustrated-cute", storiesStyle: "milestone-cards", galleryStyle: "film-roll-carousel", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "wax-seal-signature", sfxTheme: "gentle-nature" },
  },
  {
    id: "rustic-pine",
    title: "Rustic Pine Country",
    sourceOrigin: "HariKita Original",
    archetypeId: "rustic",
    category: "Rustic Vintage",
    previewImageUrl: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=600",
    colors: {
      primary: "#435240",
      secondary: "#62755E",
      accent: "#A67A53",
      background: "#F6F7F4",
      text: "#1A2119",
      cardBg: "#FFFFFF",
      border: "#D6DED4",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-serif" },
    ornamentStyle: "leaves",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FloatingCard", exitAnimId: "gate-open", entryAnimId: "fade-in", bgVariant: "pine-green" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "twin-arch-gate", mapStyle: "minimalist-guide", storiesStyle: "magazine-article", galleryStyle: "mosaic-hero", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "gentle-nature" },
  },

  // ==========================================
  // 7. CELESTIAL (8 Presets)
  // ==========================================
  {
    id: "aeternum-vita",
    title: "Aeternum Vita Cosmic",
    sourceOrigin: "HelloGuest",
    archetypeId: "celestial",
    category: "Celestial Starlight",
    previewImageUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=600",
    colors: {
      primary: "#6366F1",
      secondary: "#818CF8",
      accent: "#FDE047",
      background: "#020617",
      text: "#F8FAFC",
      cardBg: "#0F172A",
      border: "#1E293B",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FullBleedText", exitAnimId: "dissolve-particles", entryAnimId: "scale-in", bgVariant: "deep-space-indigo" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "minimalist-guide", storiesStyle: "magazine-article", galleryStyle: "film-roll-carousel", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "primus-noctis",
    title: "Primus Noctis Constellation",
    sourceOrigin: "HelloGuest",
    archetypeId: "celestial",
    category: "Celestial Starlight",
    previewImageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600",
    colors: {
      primary: "#8B5CF6",
      secondary: "#A78BFA",
      accent: "#CCA873",
      background: "#090514",
      text: "#FDF8FF",
      cardBg: "#170E2E",
      border: "#2E1B59",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "zoom-away", entryAnimId: "rise-up", bgVariant: "deep-cosmic-violet" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "vertical-timeline", mapStyle: "interactive-clean", storiesStyle: "filmstrip-scroll", galleryStyle: "mosaic-hero", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "modern-pop" },
  },
  {
    id: "lunar-melody",
    title: "Lunar Melody Eclipse",
    sourceOrigin: "HariKita Original",
    archetypeId: "celestial",
    category: "Celestial Starlight",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#38BDF8",
      secondary: "#7DD3FC",
      accent: "#FCD34D",
      background: "#030712",
      text: "#F9FAFB",
      cardBg: "#111827",
      border: "#1F2937",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FullBleedText", exitAnimId: "flip-3d", entryAnimId: "rotate-in", bgVariant: "lunar-slate" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "calendar-grid", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "polaroid-scatter", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "stellar-nova",
    title: "Stellar Nova Nebula",
    sourceOrigin: "UndanganDigital",
    archetypeId: "celestial",
    category: "Celestial Starlight",
    previewImageUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600",
    colors: {
      primary: "#EC4899",
      secondary: "#F472B6",
      accent: "#FBBF24",
      background: "#12030B",
      text: "#FFF1F7",
      cardBg: "#240918",
      border: "#4A1433",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "curtain-reveal", entryAnimId: "fall-in", bgVariant: "hot-nebula-pink" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "twin-arch-gate", mapStyle: "minimalist-guide", storiesStyle: "milestone-cards", galleryStyle: "masonry-staggered", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "midnight-blue",
    title: "Midnight Blue Horizon",
    sourceOrigin: "HelloGuest",
    archetypeId: "celestial",
    category: "Celestial Starlight",
    previewImageUrl: "https://images.unsplash.com/photo-1529636798458-92182e662485?q=80&w=600",
    colors: {
      primary: "#2563EB",
      secondary: "#60A5FA",
      accent: "#F59E0B",
      background: "#050C1A",
      text: "#EFF6FF",
      cardBg: "#0C1B38",
      border: "#19356E",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FullBleedText", exitAnimId: "gate-open", entryAnimId: "doors-close", bgVariant: "midnight-deep-blue" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "boarding-pass", mapStyle: "interactive-clean", storiesStyle: "magazine-article", galleryStyle: "film-roll-carousel", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "modern-pop" },
  },
  {
    id: "velvet-noir",
    title: "Velvet Noir Galaxy",
    sourceOrigin: "HariKita Original",
    archetypeId: "celestial",
    category: "Celestial Starlight",
    previewImageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=600",
    colors: {
      primary: "#A855F7",
      secondary: "#C084FC",
      accent: "#CCA873",
      background: "#08040C",
      text: "#FAF5FF",
      cardBg: "#150C21",
      border: "#2E1A47",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "page-turn", entryAnimId: "unfurl", bgVariant: "purple-void" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "vertical-timeline", mapStyle: "illustrated-cute", storiesStyle: "filmstrip-scroll", galleryStyle: "mosaic-hero", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "aurora-glow",
    title: "Aurora Glow Borealis",
    sourceOrigin: "UndanganDigital",
    archetypeId: "celestial",
    category: "Celestial Starlight",
    previewImageUrl: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?q=80&w=600",
    colors: {
      primary: "#10B981",
      secondary: "#34D399",
      accent: "#A7F3D0",
      background: "#02120C",
      text: "#ECFDF5",
      cardBg: "#06291C",
      border: "#0E543A",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "FullBleedText", exitAnimId: "scroll-roll", entryAnimId: "slide-left", bgVariant: "aurora-emerald" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "calendar-grid", mapStyle: "minimalist-guide", storiesStyle: "chat-journey", galleryStyle: "polaroid-scatter", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "eclipse-gold",
    title: "Eclipse Solar Corona",
    sourceOrigin: "HariKita Original",
    archetypeId: "celestial",
    category: "Celestial Starlight",
    previewImageUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=600",
    colors: {
      primary: "#F59E0B",
      secondary: "#FBBF24",
      accent: "#FDE68A",
      background: "#0D0902",
      text: "#FFFBEB",
      cardBg: "#1F1607",
      border: "#47330F",
    },
    typography: { headingFont: "font-serif", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "CircleMonogram", exitAnimId: "fade-drop", entryAnimId: "fade-in", bgVariant: "solar-corona-black" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "twin-arch-gate", mapStyle: "interactive-clean", storiesStyle: "milestone-cards", galleryStyle: "masonry-staggered", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "modern-pop" },
  },

  // ==========================================
  // 8. CUTE ILLUSTRATED (8 Presets)
  // ==========================================
  {
    id: "marielle-forest",
    title: "Marielle Forest Tale",
    sourceOrigin: "HelloGuest",
    archetypeId: "cute-illustrated",
    category: "Cute Illustrated",
    previewImageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=600",
    colors: {
      primary: "#EC4899",
      secondary: "#F472B6",
      accent: "#38BDF8",
      background: "#FFF8F5",
      text: "#1E293B",
      cardBg: "#FFFFFF",
      border: "#FFE4E6",
    },
    typography: { headingFont: "font-sans", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "KawaiiCard", exitAnimId: "zoom-away", entryAnimId: "scale-in", bgVariant: "soft-pink-pastel" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "boarding-pass", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "polaroid-scatter", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "alleya-sweet",
    title: "Alleya Sweet Romance",
    sourceOrigin: "HelloGuest",
    archetypeId: "cute-illustrated",
    category: "Cute Illustrated",
    previewImageUrl: "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=600",
    colors: {
      primary: "#F43F5E",
      secondary: "#FB7185",
      accent: "#FBBF24",
      background: "#FFF5F7",
      text: "#1F2937",
      cardBg: "#FFFFFF",
      border: "#FFE4E6",
    },
    typography: { headingFont: "font-sans", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "PolaroidPhoto", exitAnimId: "page-turn", entryAnimId: "fall-in", bgVariant: "candy-red" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "vertical-timeline", mapStyle: "minimalist-guide", storiesStyle: "filmstrip-scroll", galleryStyle: "masonry-staggered", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "manga-sweet",
    title: "Manga Sweet Kawaii",
    sourceOrigin: "UndanganDigital",
    archetypeId: "cute-illustrated",
    category: "Cute Illustrated",
    previewImageUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=600",
    colors: {
      primary: "#FB7185",
      secondary: "#FDA4AF",
      accent: "#67E8F9",
      background: "#FFF9FA",
      text: "#334155",
      cardBg: "#FFFFFF",
      border: "#FFE4E8",
    },
    typography: { headingFont: "font-sans", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "KawaiiCard", exitAnimId: "curtain-reveal", entryAnimId: "slide-left", bgVariant: "manga-pastel" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "calendar-grid", mapStyle: "interactive-clean", storiesStyle: "milestone-cards", galleryStyle: "film-roll-carousel", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "modern-pop" },
  },
  {
    id: "cartoon-maps-kebumen",
    title: "Cute Cartoon Maps Kebumen",
    sourceOrigin: "HariKita Original",
    archetypeId: "cute-illustrated",
    category: "Cute Illustrated",
    previewImageUrl: "https://images.unsplash.com/photo-1537633552985-df8429e8048b?q=80&w=600",
    colors: {
      primary: "#EC4899",
      secondary: "#38BDF8",
      accent: "#F59E0B",
      background: "#FFFBF7",
      text: "#0F172A",
      cardBg: "#FFFFFF",
      border: "#FED7AA",
    },
    typography: { headingFont: "font-sans", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "PolaroidPhoto", exitAnimId: "fade-drop", entryAnimId: "rise-up", bgVariant: "map-colorful" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "twin-arch-gate", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "mosaic-hero", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "pastel-joy",
    title: "Pastel Joy Confetti",
    sourceOrigin: "HelloGuest",
    archetypeId: "cute-illustrated",
    category: "Cute Illustrated",
    previewImageUrl: "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=600",
    colors: {
      primary: "#8B5CF6",
      secondary: "#A78BFA",
      accent: "#F43F5E",
      background: "#FAF7FF",
      text: "#1E1B4B",
      cardBg: "#FFFFFF",
      border: "#EDE9FE",
    },
    typography: { headingFont: "font-sans", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "KawaiiCard", exitAnimId: "flip-3d", entryAnimId: "rotate-in", bgVariant: "violet-joy" },
    sectionConfig: { coupleStyle: "royal-medallion", scheduleStyle: "boarding-pass", mapStyle: "minimalist-guide", storiesStyle: "magazine-article", galleryStyle: "polaroid-scatter", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "sweet-bubble",
    title: "Sweet Bubble Heart",
    sourceOrigin: "UndanganDigital",
    archetypeId: "cute-illustrated",
    category: "Cute Illustrated",
    previewImageUrl: "https://images.unsplash.com/photo-1509927083803-4bd519298ac4?q=80&w=600",
    colors: {
      primary: "#F472B6",
      secondary: "#FB7185",
      accent: "#38BDF8",
      background: "#FFF5F9",
      text: "#1F2937",
      cardBg: "#FFFFFF",
      border: "#FCE7F3",
    },
    typography: { headingFont: "font-sans", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "PolaroidPhoto", exitAnimId: "dissolve-particles", entryAnimId: "doors-close", bgVariant: "bubblegum-pink" },
    sectionConfig: { coupleStyle: "split-diagonal", scheduleStyle: "vertical-timeline", mapStyle: "interactive-clean", storiesStyle: "filmstrip-scroll", galleryStyle: "masonry-staggered", giftStyle: "embossed-cards", guestbookStyle: "luxury-scrollbook", closingStyle: "wax-seal-signature", sfxTheme: "modern-pop" },
  },
  {
    id: "cotton-candy",
    title: "Cotton Candy Clouds",
    sourceOrigin: "HariKita Original",
    archetypeId: "cute-illustrated",
    category: "Cute Illustrated",
    previewImageUrl: "https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=600",
    colors: {
      primary: "#38BDF8",
      secondary: "#818CF8",
      accent: "#F472B6",
      background: "#F0F9FF",
      text: "#0C4A6E",
      cardBg: "#FFFFFF",
      border: "#E0F2FE",
    },
    typography: { headingFont: "font-sans", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "KawaiiCard", exitAnimId: "slide-down", entryAnimId: "unfurl", bgVariant: "sky-cotton" },
    sectionConfig: { coupleStyle: "arch-classic", scheduleStyle: "calendar-grid", mapStyle: "illustrated-cute", storiesStyle: "chat-journey", galleryStyle: "film-roll-carousel", giftStyle: "angpao-envelope", guestbookStyle: "sticky-notes", closingStyle: "cute-waving-outro", sfxTheme: "modern-pop" },
  },
  {
    id: "doodle-love",
    title: "Doodle Love Notes",
    sourceOrigin: "HelloGuest",
    archetypeId: "cute-illustrated",
    category: "Cute Illustrated",
    previewImageUrl: "https://images.unsplash.com/photo-1518895949257-7621c3c786d7?q=80&w=600",
    colors: {
      primary: "#FB923C",
      secondary: "#F43F5E",
      accent: "#FBBF24",
      background: "#FFFBF7",
      text: "#1C1917",
      cardBg: "#FFFFFF",
      border: "#FFEDD5",
    },
    typography: { headingFont: "font-sans", bodyFont: "font-sans" },
    ornamentStyle: "cute-stars",
    defaultAudioTrack: "https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3?filename=romantic-piano-112199.mp3",
    coverConfig: { layoutId: "PolaroidPhoto", exitAnimId: "scroll-roll", entryAnimId: "fade-in", bgVariant: "orange-doodle" },
    sectionConfig: { coupleStyle: "polaroid-sticker", scheduleStyle: "twin-arch-gate", mapStyle: "minimalist-guide", storiesStyle: "milestone-cards", galleryStyle: "mosaic-hero", giftStyle: "clean-pills", guestbookStyle: "minimal-feed", closingStyle: "poetic-photo-outro", sfxTheme: "modern-pop" },
  },
];
