/**
 * Data dummy kaya untuk seeder: paket layanan & portofolio per kategori vendor.
 *
 * Setiap kategori (11 kategori HariKita) memiliki ≥25 varian paket layanan dan
 * 10 template portofolio. Seeder akan men-generate harga bervariasi per vendor
 * agar tiap vendor punya katalog & feed yang kaya.
 */

export interface ServiceTemplate {
  name: string;
  description: string;
  /** Faktor harga relatif terhadap basePrice vendor. */
  priceFactor: number;
  unitType: "all_in" | "pax" | "baki" | "pcs" | "jam" | "set";
  minUnit?: number;
  maxUnit?: number;
  includes: string[];
  slaDays: number;
}

/** Tuple: [title, locationTag, categoryTag, styleTags, caption] */
export type PortfolioTemplate = [string, string, string, string[], string];

// ─────────────────────────────────────────────────────────────────────────────
// PAKET LAYANAN PER KATEGORI (25 varian masing-masing)
// ─────────────────────────────────────────────────────────────────────────────

const IMG = {
  prewed: [
    "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800",
    "https://images.unsplash.com/photo-1606216794074-735e91aa2c92?q=80&w=800",
    "https://images.unsplash.com/photo-1583939003579-730e3918a45a?q=80&w=800",
    "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=800",
    "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=800",
    "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=800",
    "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?q=80&w=800",
    "https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=800",
  ],
  busana: [
    "https://images.unsplash.com/photo-1594552072238-b8a33785b261?q=80&w=800",
    "https://images.unsplash.com/photo-1591369822096-ffd140ec948f?q=80&w=800",
    "https://images.unsplash.com/photo-1595777457583-95e059d581b8?q=80&w=800",
    "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?q=80&w=800",
    "https://images.unsplash.com/photo-1509319117193-57bab727e09d?q=80&w=800",
    "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?q=80&w=800",
    "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=800",
    "https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=800",
  ],
  mua: [
    "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?q=80&w=800",
    "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?q=80&w=800",
    "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?q=80&w=800",
    "https://images.unsplash.com/photo-1503236823255-94609f598e71?q=80&w=800",
    "https://images.unsplash.com/photo-1560066984-138dadb4c035?q=80&w=800",
    "https://images.unsplash.com/photo-1526045478516-99145907023c?q=80&w=800",
    "https://images.unsplash.com/photo-1596704017254-9b121068fb31?q=80&w=800",
    "https://images.unsplash.com/photo-1457972729786-0411a3b2b626?q=80&w=800",
  ],
  seserahan: [
    "https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=800",
    "https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=800",
    "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=800",
    "https://images.unsplash.com/photo-1607083206968-13611e3d76db?q=80&w=800",
    "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800",
    "https://images.unsplash.com/photo-1513883049090-d0b7439799bf?q=80&w=800",
    "https://images.unsplash.com/photo-1607006344380-b6775a0824ce?q=80&w=800",
    "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?q=80&w=800",
  ],
  dokumentasi: [
    "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?q=80&w=800",
    "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?q=80&w=800",
    "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?q=80&w=800",
    "https://images.unsplash.com/photo-1537633552985-df8429e8048b?q=80&w=800",
    "https://images.unsplash.com/photo-1519741497674-611481863552?q=80&w=800",
    "https://images.unsplash.com/photo-1554048612-b6a482bc67e5?q=80&w=800",
    "https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=800",
    "https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?q=80&w=800",
  ],
  dekorasi: [
    "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?q=80&w=800",
    "https://images.unsplash.com/photo-1478146896981-b80fe463b330?q=80&w=800",
    "https://images.unsplash.com/photo-1520854221256-17451cc331bf?q=80&w=800",
    "https://images.unsplash.com/photo-1510076857177-7470076d4098?q=80&w=800",
    "https://images.unsplash.com/photo-1533936151986-9563d8b9a3b5?q=80&w=800",
    "https://images.unsplash.com/photo-1465146344425-f00d5f5c8f07?q=80&w=800",
    "https://images.unsplash.com/photo-1508610048659-a06b669e3321?q=80&w=800",
    "https://images.unsplash.com/photo-1487530811176-3780de880c2d?q=80&w=800",
  ],
  katering: [
    "https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=800",
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=800",
    "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=800",
    "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800",
    "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=800",
    "https://images.unsplash.com/photo-1467003909585-2f8a72700288?q=80&w=800",
    "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?q=80&w=800",
    "https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=800",
  ],
  cake: [
    "https://images.unsplash.com/photo-1535141192574-5d4897c12636?q=80&w=800",
    "https://images.unsplash.com/photo-1565958011703-44f9829ba187?q=80&w=800",
    "https://images.unsplash.com/photo-1621303837174-89787a7d4729?q=80&w=800",
    "https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800",
    "https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=800",
    "https://images.unsplash.com/photo-1558301211-0d8c8ddee6ec?q=80&w=800",
    "https://images.unsplash.com/photo-1587668178277-295251f900ce?q=80&w=800",
    "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=800",
  ],
  souvenir: [
    "https://images.unsplash.com/photo-1549465220-1a8b9238cd48?q=80&w=800",
    "https://images.unsplash.com/photo-1607083206968-13611e3d76db?q=80&w=800",
    "https://images.unsplash.com/photo-1513883049090-d0b7439799bf?q=80&w=800",
    "https://images.unsplash.com/photo-1607006483220-6e7e4e2aab88?q=80&w=800",
    "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?q=80&w=800",
    "https://images.unsplash.com/photo-1481437156560-3205f6a55735?q=80&w=800",
    "https://images.unsplash.com/photo-1573053009372-3dc4dc2d4e4a?q=80&w=800",
    "https://images.unsplash.com/photo-1521334884684-d80222895322?q=80&w=800",
  ],
  undangan: [
    "https://images.unsplash.com/photo-1607190074257-dd4b7af0309f?q=80&w=800",
    "https://images.unsplash.com/photo-1522673607200-164d1b6ce486?q=80&w=800",
    "https://images.unsplash.com/photo-1529636798458-92182e662485?q=80&w=800",
    "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=800",
    "https://images.unsplash.com/photo-1587145820266-a5951ee6f620?q=80&w=800",
    "https://images.unsplash.com/photo-1512295767273-ac109ac3acfa?q=80&w=800",
    "https://images.unsplash.com/photo-1519225421980-715cb0215aed?q=80&w=800",
    "https://images.unsplash.com/photo-1522542739923-6d1d1d2b36c4?q=80&w=800",
  ],
  map: [
    "https://images.unsplash.com/photo-1524661135-423995f22d0b?q=80&w=800",
    "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?q=80&w=800",
    "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?q=80&w=800",
    "https://images.unsplash.com/photo-1569336415962-a4bd9f69cd83?q=80&w=800",
    "https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?q=80&w=800",
    "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=800",
    "https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?q=80&w=800",
    "https://images.unsplash.com/photo-1508614589041-895b88991e3e?q=80&w=800",
  ],
};

/** Helper bikin 25 varian cepat dari daftar nama + deskripsi generik. */
function make25(
  names: string[],
  baseDesc: string,
  unitType: ServiceTemplate["unitType"],
  includes: string[],
  priceFactors: number[]
): ServiceTemplate[] {
  return names.map((name, i) => ({
    name,
    description: `${baseDesc}`,
    priceFactor: priceFactors[i % priceFactors.length],
    unitType,
    includes,
    slaDays: 3 + (i % 7),
  }));
}

export const SERVICE_TEMPLATES: Record<string, ServiceTemplate[]> = {
  "Pre-wedding": make25(
    [
      "Paket Studio All-In Kasual",
      "Outdoor Pantai Menganti Half Day",
      "Outdoor Bukit Menara Sunrise",
      "Prewed Casual Street Style",
      "Prewed Adat Jawa Klasik",
      "Prewed Adat Sunda Modern",
      "Prewed Konsep Garden Party",
      "Prewed Full Day + Drone",
      "Prewed Night & Light Painting",
      "Prewed Minimalis Studio Putih",
      "Prewed Vintage Sepia Retro",
      "Prewed Destination Pantai Ayah",
      "Prewed Museum & Heritage Kebumen",
      "Prewed Prewedding Cinematic Film",
      "Prewed Save The Date Session",
      "Prewed Maternity & Engagement",
      "Prewed Konsep Kuliner Kebumen",
      "Prewed Sungai & Air Terjun",
      "Prewed Sawah Golden Hour",
      "Prewed Kafe Aesthetic Lokal",
      "Prewed Konsep Adat Palembang",
      "Prewed 3 Busana + 40 Foto",
      "Prewed 2 Lokasi Sehari",
      "Prewed Teaser Reels TikTok",
      "Prewed Album Premium Magnetic",
    ],
    "Sesi foto pre-wedding dengan fotografer & editor profesional HariKita Kebumen.",
    "all_in",
    ["Fotografer", "Editor retouch", "Album digital", "Softcopy semua file"],
    [0.7, 0.9, 1, 1.15, 1.3, 1.6, 0.85, 1.45]
  ),
  "Busana Pengantin & Fitting": make25(
    [
      "Sewa Kebaya Akad Modern",
      "Sewa Beskap Adat Jawa",
      "Paket Lengkap Akad + Resepsi",
      "Sewa Perdana Kebaya Full Beaded",
      "Kebaya Sunda Sinjang",
      "Bescap Lengkap + Kain Batik",
      "Sewa Gaun Barat Pengantin",
      "Seragam Orang Tua 2 Pasang",
      "Sewa Busana Resepsi Muslimah",
      "Kebaya Kutubaru Vintage",
      "Packages Busana Adat Solo",
      "Sewa Beskap + Blangkon + Keris",
      "Kebaya Sheer Modern Fit",
      "Sewa Baju Bridesmaid 5 Orang",
      "Sewa Busana Adat Palembang",
      "Sewa Busana Akad Outdoor",
      "Kebaya Do + Hair Accessories",
      "Sewa Baju Sampur Melayu",
      "Paket Semua In One Family",
      "Sewa Busana Adat Minang",
      "Fitting + Rias Tambahan",
      "Sewa Busana Bachelor & Bridal",
      "Custom Kebaya Ukuran",
      "Sewa Celana & Sepatu Adat",
      "Gown Rental Premium Import",
    ],
    "Busana pengantin & fitting dengan koleksi adat dan modern lengkap.",
    "all_in",
    ["Sewa busana", "Aksesori", "2x sesi fitting", "Jaminan bersih & wangi"],
    [0.6, 0.8, 1, 1.2, 1.4, 1.7, 0.9, 1.5]
  ),
  "Makeup Artist (MUA)": make25(
    [
      "Rias Pengantin Soft Glam",
      "Rias Pengantin Korean Glow",
      "Rias Pengantin Adat Jawa",
      "Rias Pengantin Adat Sunda",
      "Rias Hijab Syar'i Do",
      "Rias Akad Saja",
      "Rias Resepsi Saja",
      "Rias Akad + Resepsi",
      "Rias + Hair Do Lengkap",
      "Rias Ibu Pengantin",
      "Rias Bridesmaid 3 Orang",
      "Rias Tester Book 15 Menit",
      "Rias Engagement / Lamaran",
      "Rias Bulu Mata & Beard Groom",
      "Rias Konsep Flawless Natural",
      "Rias Bold Glam Malam",
      "Rias Adat Palembang",
      "Rias Akad Muslimah",
      "Rias + Retouch Makeup Keluarga",
      "Rias Upacara Siraman Adat",
      "Rias Fotografi High Definition",
      "Rias + Hijab Styling Modern",
      "Rias Bridal Full Airbrush",
      "Rias dan Nail Art Sederhana",
      "Rias Paket Lengkap + Retouch",
    ],
    "Melati segar, hijab do, dan touch-up standby oleh MUA bersertifikat Kebumen.",
    "all_in",
    ["Rias pengantin", "Hijab/hair do", "Melati segar", "Touch-up standby"],
    [0.7, 0.9, 1, 1.15, 1.35, 1.6, 0.85, 1.45]
  ),
  "Kotak Seserahan & Mahar": make25(
    [
      "Sewa Baki Akrilik 5 Kotak",
      "Sewa Baki Akrilik 7 Kotak",
      "Sewa Baki Akrilik 9 Kotak",
      "Hias Baki Kayu Jati",
      "Pigura Mahar Custom",
      "Box Seserahan Rotan",
      "Kotak Seserahan Kaca",
      "Tray Hantaran Satin",
      "Baki Mahar Ukir Jepara",
      "Seserahan Daster Set",
      "Kotak Cincin Beludru",
      "Hantaran Buah Mewah",
      "Seserahan Alat Sholat",
      "Kotak Make Up Eksklusif",
      "Hias Seserahan Adat Jawa",
      "Baki Prasmanan Perak",
      "Seserahan Perlengkapan Mandi",
      "Box Hantaran Kue Kering",
      "Tray Bunga Kering Estetik",
      "Seserahan Mukena Bordir",
      "Kotak Tasbih & Qur'an",
      "Hantaran Snack Premium",
      "Seserahan Sepatu & Tas",
      "Baki Mahar Emas Rias",
      "Paket Hias Semua Baki Lengkap",
    ],
    "Sewa & hias baki seserahan/mahar dengan sentuhan estetik.",
    "baki",
    ["Sewa baki", "Hias ornamen", "Penataan hantaran", "Jaminan rapi"],
    [0.5, 0.7, 0.9, 1, 1.3, 1.6, 0.6, 1.2]
  ),
  "Dokumentasi Foto-Video": make25(
    [
      "Liputan Hari H Foto+Video",
      "Cinematic Wedding Film 3 Menit",
      "Teaser Reels 60 Detik",
      "Foto Akad Saja",
      "Foto Resepsi Saja",
      "Full Day 2 Fotografer",
      "Drone Aerial Footage",
      "Live Streaming 1 Kamera",
      "Slow Motion Golden Hour",
      "Album Foto Premium",
      "Flashdisk Exclusif Box",
      "Foto Keluarga & Tamu",
      "Video Dokumenter 15 Menit",
      "Same Day Edit",
      "Foto Engangement",
      "Behind The Scene Crew",
      "Photobooth + Print",
      "Video Instagram Story",
      "Dokumentasi Siraman Adat",
      "Dokumentasi Lamaran",
      "Foto Studio Keluarga",
      "Video TikTok Vertical",
      "2 Fotografer + 1 Videografer",
      "Pre-Event Test Shooting",
      "Paket Lengkap Semua Output",
    ],
    "Dokumentasi foto & video cinematic oleh kru profesional.",
    "all_in",
    ["Kru liputan", "Editing", "Semua file", "Titik penyimpanan cloud"],
    [0.7, 0.9, 1, 1.15, 1.35, 1.6, 0.85, 1.45]
  ),
  "Dekorasi & Florist": make25(
    [
      "Dekorasi Pelaminan Intimate 4-6m",
      "Backdrop Lamaran 3x2.5m",
      "Dekorasi Akad Minimalis",
      "Dekorasi Resepsi Modern",
      "Pelaminan Adat Jawa",
      "Buket Bunga Segar Tangan",
      "Aisle & Standing Flower",
      "Dekorasi Gerbang Penerima",
      "Meja Akad Rustic",
      "Dekorasi Tenda & Lighting",
      "Bunga Meja Tamu",
      "Hias Kursi Pengantin",
      "Dekorasi Adat Sunda",
      "Welcome Sign Estetik",
      "Dekorasi Konsep Bali Garden",
      "Papan Bunga Ucapan",
      "Dekorasi Konsep Rustic",
      "Instalasi Bunga Gantung",
      "Dekorasi Photobooth",
      "Corsage & Boutineer",
      "Dekorasi Ruang Resepsi Full",
      "Flower Wall Backdrop",
      "Dekorasi Konsep Bohemian",
      "Dekorasi Pastel Soft Tone",
      "Paket Dekorasi All-In",
    ],
    "Dekorasi & florist dengan rangkaian bunga segar.",
    "all_in",
    ["Konsep dekorasi", "Bunga segar", "Tim pemasangan", "Bongkar ulang"],
    [0.6, 0.8, 1, 1.2, 1.5, 1.8, 0.9, 1.4]
  ),
  "Katering & Food Stalls": make25(
    [
      "Prasmanan Harmoni 100 Pax",
      "Prasmanan Premium 200 Pax",
      "Buffet Adat Jawa 150 Pax",
      "Nasi Box Sederhana 50 Box",
      "Food Stall Gorengan",
      "Food Stall Minuman & Es",
      "Sample Box Test Food",
      "Prasmanan Seafood",
      "Live Cooking Satay",
      "Pondokan Nasi Liwet",
      "Food Truck Mini",
      "Prasmanan Vegetarian",
      "Dessert Bar & Pancake",
      "Catering Adat Sunda",
      "Prasmanan Kebumen Heritage",
      "Coffee Bar & Barista",
      "Snack Box Meeting",
      "Food Stall Sate & Tongseng",
      "Prasmanan Muslim Halal",
      "Bebek Bumbu Hitam Spesial",
      "Prasmanan 300 Pax Full",
      "Es Dawet Ireng Kebumen",
      "Food Spread International",
      "Bubur & Jajan Pasar",
      "Paket Catering Lengkap",
    ],
    "Katering dengan menu lokal Kebumen dan internasional.",
    "pax",
    ["Menu lengkap", "Perlengkapan prasmanan", "Tim pelayanan", "Food tester"],
    [0.6, 0.8, 1, 1.2, 1.5, 1.8, 0.9, 1.4]
  ),
  "Cakes & Dessert Corner": make25(
    [
      "Tiered Wedding Cake 3 Tingkat",
      "Sweet Corner 100 pax",
      "Cake Taster Box 5 Varian",
      "Engagement Cake 2 Tingkat",
      "Dessert Table Mini",
      "Tart Buah Premium",
      "Cupcake Set 50 pcs",
      "Macaron Tower",
      "Bolu Adat Traditional",
      "Cheese Cake Whole",
      "Brownies Box Souvenir",
      "Dessert Cup Set",
      "Kue Basah Tradisional",
      "Cake Papan Ucapan Custom",
      "Ice Cream Corner",
      "Waffle & Crepe Station",
      "Pudding Layer Cantik",
      "Cookies Jar Custom Label",
      "Chocolate Fountain Mini",
      "Tiered Cake 5 Tingkat",
      "Kue Ulang Tahun Pengantin",
      "Lapet & Jajan Pasar",
      "Cake Tasting Private",
      "Sweet Bar Rustic",
      "Paket Cake & Dessert Lengkap",
    ],
    "Kue acara & dessert corner dengan resep rumahan premium.",
    "all_in",
    ["Kue custom", "Setup dessert", "Peralatan display", "Penyajian"],
    [0.6, 0.8, 1, 1.2, 1.5, 1.8, 0.9, 1.4]
  ),
  "Souvenir & Favors": make25(
    [
      "Pouch Linen Custom 50 pcs",
      "Scented Candle Mini 50 pcs",
      "Kerajinan Anyaman Pandan",
      "Gantungan Kunci Akrilik",
      "Tumbler Mini Custom",
      "Souvenir Hand Sanitizer",
      "Favor Box Estetik 100 pcs",
      "Sabun Bunga Lavender",
      "Dompet Mini Custom Inisial",
      "Souvenir Lumpia Box",
      "Tas Kain Kanvas Print",
      "Bibit Tanaman Mini",
      "Souvenir Kipas Cantik",
      "Gelas Mini Custom",
      "Kotak Makanan Vintage",
      "Souvenir Teh Premium",
      "Pensil Custom Nama",
      "Boneka Kecil Bunga",
      "Souvenir Kain Batik",
      "Kerajinan Rotan Mini",
      "Souvenir Rendang Kemasan",
      "Bunga Kering Press",
      "Lilin Aromaterapi Gift",
      "Souvenir Bordir Nama",
      "Paket Souvenir Lengkap",
    ],
    "Souvenir & wedding favors eksklusif lokal Kebumen.",
    "pcs",
    ["Desain custom", "Bahan pilihan", "Kemasan estetik", "Label nama"],
    [0.5, 0.7, 0.9, 1, 1.3, 1.6, 0.6, 1.2]
  ),
  "Undangan Digital & Amplop": make25(
    [
      "Undangan Digital 1 Sesi",
      "Undangan Digital Multi Sesi",
      "Undangan Cetak Wax Seal",
      "Bundel Digital + Cetak",
      "Undangan Hardcover Custom",
      "Amplop Digital QRIS",
      "Undangan Video Motion",
      "Undangan Minimalis Typographic",
      "Undangan Floral Botanical",
      "Undangan Royal Foil Gold",
      "Undangan Adat Jawa",
      "Undangan Islamic Syar'i",
      "Undangan Metallic Premium",
      "Undangan Instant Template",
      "Amplop Fisik Soft Touch",
      "Undangan Foto Full Screen",
      "Undangan Musik & Auto Scroll",
      "Undangan RSVP Online",
      "Undangan Buku Tamu QR",
      "Undangan Custom Slug",
      "Amplop Digital + Fisik",
      "Undangan 100 Cetak",
      "Undangan 200 Cetak",
      "Undangan Premium Custom",
      "Paket Undangan All-In",
    ],
    "Undangan digital interaktif & cetak premium.",
    "pcs",
    ["Desain undangan", "Multi tamu", "RSVP online", "Amplop digital"],
    [0.5, 0.7, 0.9, 1, 1.3, 1.6, 0.6, 1.2]
  ),
  "Cute Illustrated Maps": make25(
    [
      "Ilustrasi Denah Kartun",
      "Denah + QR Google Maps",
      "Denah Bertema Pantai",
      "Denah Bertema Sawah",
      "Denah Mobile Friendly",
      "Denah Animasi Bergerak",
      "Denah Adat Jawa",
      "Denah Minimalis Pastel",
      "Denah Watercolor",
      "Denah 3 Titik Lokasi",
      "Denah Multi Venue",
      "Denah + Waze Link",
      "Denah Couple Character",
      "Denah Cartoon Family",
      "Denah Animasi Loading",
      "Denah + Countdown",
      "Denah Botanical",
      "Denah Urban Cute",
      "Denah Hand-drawn Style",
      "Denah Print + Digital",
      "Denah Instagram Story",
      "Denah Custom Warna",
      "Denah Custom Ikon",
      "Denah Premium Full Ilustrasi",
      "Paket Denah Lengkap + QR",
    ],
    "Generator denah lokasi kartun lucu terintegrasi QR maps.",
    "all_in",
    ["Ilustrasi custom", "QR navigasi", "Versi cetak", "Versi digital"],
    [0.6, 0.8, 1, 1.2, 1.5, 1.8, 0.9, 1.4]
  ),
};

// ─────────────────────────────────────────────────────────────────────────────
// PORTOFOLIO PER KATEGORI (10 template masing-masing)
// ─────────────────────────────────────────────────────────────────────────────

export const PORTFOLIO_TEMPLATES: Record<string, PortfolioTemplate[]> = {
  "Pre-wedding": [
    ["Golden Hour di Menganti", "Pantai Menganti", "Pre-wedding", ["sunset", "pantai", "golden"], "Sesi senja romantis di bibir Pantai Menganti."],
    ["Bukit Menara Sunrise", "Bukit Menara", "Pre-wedding", ["sunrise", "bukit", "outdoor"], "Menangkap kabut pagi di perbukitan Kebumen."],
    ["Casual Street Kebumen Kota", "Alun-alun Kebumen", "Pre-wedding", ["casual", "urban", "street"], "Gaya santai dengan latar kota tua."],
    ["Adat Jawa Klasik", "Pendopo Kabupaten", "Pre-wedding", ["adat", "jawa", "tradisional"], "Balutan kebaya & beskap penuh filosofi."],
    ["Rustic Sawah Golden", "Desa Karanganyar", "Pre-wedding", ["rustic", "sawah", "alam"], "Pematang sawah dengan cahaya keemasan."],
    ["Vintage Sepia", "Studio Kebumen", "Pre-wedding", ["vintage", "studio", "retro"], "Nuansa jadul dengan tone sepia hangat."],
    ["Garden Party", "Kebun Bunga Pejagoan", "Pre-wedding", ["garden", "floral", "outdoor"], "Pesta taman penuh bunga segar."],
    ["Night Light Painting", "Bukit Menara", "Pre-wedding", ["night", "light", "creative"], "Eksperimen cahaya malam yang dramatis."],
    ["Air Terjun Tersembunyi", "Desa Alian", "Pre-wedding", ["airterjun", "alam", "sejuk"], "Bingkai alam asri di air terjun lokal."],
    ["Museum Heritage Story", "Museum Kebumen", "Pre-wedding", ["heritage", "klasik", "kultural"], "Latar bangunan bersejarah yang elegan."],
  ],
  "Busana Pengantin & Fitting": [
    ["Kebaya Modern Full Beaded", "Kebumen Kota", "Busana", ["kebaya", "modern", "beaded"], "Kebaya penuh payet dengan detail mewah."],
    ["Beskap Adat Jawa", "Gombong", "Busana", ["beskap", "adat", "jawa"], "Beskap klasik lengkap blangkon & keris."],
    ["Gaun Barat Pengantin", "Kebumen Kota", "Busana", ["gaun", "barat", "elegant"], "Gaun putih dengan ekor panjang."],
    ["Kebaya Sunda Sinjang", "Kutowinangun", "Busana", ["sunda", "sinjang", "tradisional"], "Sinjang Sunda dengan sanggul modern."],
    ["Seragam Keluarga Adat", "Prembun", "Busana", ["keluarga", "adat", "seragam"], "Kekompakan busana kedua keluarga."],
    ["Kebaya Sheer Modern", "Kebumen Kota", "Busana", ["kebaya", "sheer", "modern"], "Transparan elegan dengan inner premium."],
    ["Gaun Mermaid Mewah", "Gombong", "Busana", ["mermaid", "mewah", "gaun"], "Potongan mermaid menonjolkan siluet."],
    ["Batik Couple Modern", "Kutowinangun", "Busana", ["batik", "couple", "modern"], "Batik couple motif eksklusif."],
    ["Kebaya Kutubaru Klasik", "Prembun", "Busana", ["kutubaru", "klasik", "kebaya"], "Kutubaru klasik nan anggun."],
    ["Seragam Bridesmaid Pastel", "Kebumen Kota", "Busana", ["bridesmaid", "pastel", "seragam"], "Seragam bridesmaid warna pastel."],
  ],
  "Makeup Artist (MUA)": [
    ["Soft Glam Pengantin", "Kebumen Kota", "MUA", ["softglam", "natural", "bridal"], "Rias lembut memancarkan kecantikan alami."],
    ["Korean Glow Look", "Gombong", "MUA", ["korean", "glow", "dewy"], "Kulit glowing ala Korea."],
    ["Adat Jawa Klasik", "Kebumen Kota", "MUA", ["adat", "jawa", "tradisional"], "Rias adat dengan paes & sanggul."],
    ["Hijab Syar'i Do", "Karanganyar", "MUA", ["hijab", "syari", "elegant"], "Hijab do elegan tanpa mengumbar."],
    ["Bold Glam Malam", "Kebumen Kota", "MUA", ["bold", "glam", "malam"], "Look tegas untuk resepsi malam."],
    ["Flawless Natural", "Prembun", "MUA", ["flawless", "natural", "hd"], "Makeup HD flawless tahan lama."],
    ["Rias Siraman Adat", "Kebumen Kota", "MUA", ["siraman", "adat", "tradisional"], "Rias sakral untuk prosesi siraman."],
    ["Rias Ibu & Keluarga", "Gombong", "MUA", ["keluarga", "ibu", "elegan"], "Rias anggun untuk ibu pengantin."],
    ["Airbrush Premium", "Kebumen Kota", "MUA", ["airbrush", "premium", "halus"], "Teknik airbrush halus & tahan lama."],
    ["Rias Engagement", "Karanganyar", "MUA", ["engagement", "lembut", "romantis"], "Rias manis untuk sesi lamaran."],
  ],
  "Kotak Seserahan & Mahar": [
    ["Baki Akrilik Elegan", "Kebumen Kota", "Seserahan", ["akrilik", "elegant", "hantaran"], "Baki akrilik bening dengan hias bunga."],
    ["Pigura Mahar Ukir", "Gombong", "Seserahan", ["mahar", "ukir", "custom"], "Pigura mahar ukiran Jepara."],
    ["Seserahan Rotan Natural", "Karanganyar", "Seserahan", ["rotan", "natural", "rustic"], "Box rotan anyaman tangan."],
    ["Tray Satin Mewah", "Kebumen Kota", "Seserahan", ["satin", "mewah", "tray"], "Tray satin dengan renda halus."],
    ["Hantaran Buah Segar", "Prembun", "Seserahan", ["buah", "segar", "hantaran"], "Hantaran buah tertata artistik."],
    ["Kotak Cincin Beludru", "Kebumen Kota", "Seserahan", ["cincin", "beludru", "mewah"], "Kotak cincin beludru eksklusif."],
    ["Baki Kaca Premium", "Gombong", "Seserahan", ["kaca", "premium", "baki"], "Baki kaca mewah dengan detail emas."],
    ["Hiasan Bunga Kering", "Karanganyar", "Seserahan", ["bungakering", "estetik", "hias"], "Hiasan bunga kering tahan lama."],
    ["Box Seserahan Satin", "Prembun", "Seserahan", ["satin", "box", "elegan"], "Box seserahan berselimut satin."],
    ["Tray Rotan Rustic", "Kebumen Kota", "Seserahan", ["rotan", "rustic", "tray"], "Tray rotan bergaya rustic."],
  ],
  "Dokumentasi Foto-Video": [
    ["Cinematic Wedding Film", "Kebumen Kota", "Dokumentasi", ["cinematic", "film", "video"], "Film sinematik hari bahagia."],
    ["Liputan Akad Haru", "Gombong", "Dokumentasi", ["akad", "haru", "moment"], "Momen sakral yang menyentuh."],
    ["Drone Aerial Pantai", "Pantai Ayah", "Dokumentasi", ["drone", "aerial", "pantai"], "Sudut udara memukau."],
    ["Same Day Edit", "Kebumen Kota", "Dokumentasi", ["sameday", "edit", "cepat"], "Editing kilat tayang hari itu."],
    ["Foto Keluarga Hangat", "Kebumen Kota", "Dokumentasi", ["keluarga", "hangat", "potret"], "Kebersamaan keluarga besar."],
    ["Teaser Reels Viral", "Gombong", "Dokumentasi", ["reels", "tiktok", "viral"], "Teaser 60 detik siap posting."],
    ["Dokumenter 15 Menit", "Kebumen Kota", "Dokumentasi", ["dokumenter", "lengkap", "cerita"], "Video dokumenter alur cerita lengkap."],
    ["Photobooth + Print", "Karanganyar", "Dokumentasi", ["photobooth", "print", "seru"], "Photobooth langsung cetak untuk tamu."],
    ["Slow Motion Golden", "Pejagoan", "Dokumentasi", ["slowmo", "golden", "sinematik"], "Slow motion dengan cahaya emas."],
    ["Foto Keluarga Studio", "Kebumen Kota", "Dokumentasi", ["keluarga", "studio", "potret"], "Sesi potret keluarga profesional."],
  ],
  "Dekorasi & Florist": [
    ["Pelaminan Intimate Pastel", "Kebumen Kota", "Dekorasi", ["pelaminan", "pastel", "intimate"], "Pelaminan lembut penuh bunga."],
    ["Backdrop Lamaran Rustic", "Gombong", "Dekorasi", ["backdrop", "rustic", "lamaran"], "Backdrop kayu rustic dengan flora."],
    ["Aisle Bunga Segar", "Karanganyar", "Dekorasi", ["aisle", "bunga", "segar"], "Jalur bunga segar menuju pelaminan."],
    ["Adat Jawa Klasik", "Kebumen Kota", "Dekorasi", ["adat", "jawa", "tradisional"], "Gebyok & gunungan adat Jawa."],
    ["Bohemian Garden", "Pejagoan", "Dekorasi", ["bohemian", "garden", "floral"], "Konsep bohemian penuh tanaman."],
    ["Lighting & Tenda Mewah", "Prembun", "Dekorasi", ["lighting", "tenda", "mewah"], "Tata cahaya hangat pesta malam."],
    ["Welcome Sign Estetik", "Kebumen Kota", "Dekorasi", ["welcomesign", "estetik", "minimalis"], "Papan sambutan bergaya estetik."],
    ["Flower Wall Backdrop", "Gombong", "Dekorasi", ["flowerwall", "backdrop", "bunga"], "Dinding bunga instagramable."],
    ["Instalasi Bunga Gantung", "Karanganyar", "Dekorasi", ["gantung", "bunga", "instalasi"], "Instalasi bunga gantung memukau."],
    ["Dekorasi Bohemian Garden", "Pejagoan", "Dekorasi", ["bohemian", "garden", "floral"], "Sentuhan bohemian penuh tanaman."],
  ],
  "Katering & Food Stalls": [
    ["Prasmanan Harmoni", "Kebumen Kota", "Katering", ["prasmanan", "harmoni", "lokal"], "Hidangan lokal lengkap."],
    ["Live Cooking Satay", "Gombong", "Katering", ["sate", "livecooking", "aroma"], "Sate dibakar langsung di lokasi."],
    ["Es Dawet Ireng", "Kebumen Kota", "Katering", ["dawet", "tradisional", "segar"], "Dawet ireng khas Kebumen."],
    ["Dessert Bar Manis", "Karanganyar", "Katering", ["dessert", "bar", "manis"], "Aneka hidangan penutup."],
    ["Food Truck Mini", "Prembun", "Katering", ["foodtruck", "mini", "unik"], "Food truck estetik untuk tamu."],
    ["Heritage Kebumen", "Kebumen Kota", "Katering", ["heritage", "autentik", "kebumen"], "Cita rasa warisan Kebumen."],
    ["Prasmanan Seafood", "Pantai Ayah", "Katering", ["seafood", "prasmanan", "segar"], "Hidangan laut segar pilihan."],
    ["Coffee Bar Barista", "Kebumen Kota", "Katering", ["coffee", "barista", "bar"], "Coffee bar dengan barista profesional."],
    ["Snack Box Meeting", "Gombong", "Katering", ["snackbox", "ringan", "praktis"], "Snack box praktis untuk tamu."],
    ["Bubur & Jajan Pasar", "Karanganyar", "Katering", ["jajanpasar", "tradisional", "kebumen"], "Aneka jajan pasar tradisional."],
  ],
  "Cakes & Dessert Corner": [
    ["Tiered Cake Mewah", "Kebumen Kota", "Cake", ["tiered", "mewah", "cake"], "Kue bertingkat penuh detail."],
    ["Sweet Corner Pastel", "Gombong", "Cake", ["sweetcorner", "pastel", "cantik"], "Sudut manis berwarna pastel."],
    ["Macaron Tower", "Kebumen Kota", "Cake", ["macaron", "tower", "warna"], "Menara macaron berwarna."],
    ["Cake Adat Traditional", "Karanganyar", "Cake", ["adat", "tradisional", "cake"], "Kue adat dengan sentuhan modern."],
    ["Ice Cream Corner", "Prembun", "Cake", ["icecream", "corner", "segar"], "Es krim segar untuk tamu."],
    ["Chocolate Fountain", "Kebumen Kota", "Cake", ["chocolate", "fountain", "elegan"], "Air terjun cokelat elegan."],
    ["Cupcake Set Warna", "Gombong", "Cake", ["cupcake", "warna", "cantik"], "Cupcake berwarna cerah."],
    ["Tart Buah Premium", "Kebumen Kota", "Cake", ["tart", "buah", "premium"], "Tart buah segar premium."],
    ["Waffle & Crepe Station", "Karanganyar", "Cake", ["waffle", "crepe", "station"], "Stasiun waffle & crepe hangat."],
    ["Cookies Jar Custom", "Prembun", "Cake", ["cookies", "jar", "custom"], "Kue kering dalam jar berlabel."],
  ],
  "Souvenir & Favors": [
    ["Pouch Linen Custom", "Kebumen Kota", "Souvenir", ["pouch", "linen", "custom"], "Pouch linen berinisial."],
    ["Scented Candle Mini", "Gombong", "Souvenir", ["candle", "aroma", "mini"], "Lilin aroma terapi mini."],
    ["Anyaman Pandan", "Karanganyar", "Souvenir", ["anyaman", "lokal", "pandan"], "Kerajinan anyaman lokal."],
    ["Tumbler Custom", "Kebumen Kota", "Souvenir", ["tumbler", "custom", "elegan"], "Tumbler cetak nama tamu."],
    ["Favor Box Estetik", "Prembun", "Souvenir", ["box", "estetik", "gift"], "Kotak favor cantik."],
    ["Souvenir Batik", "Kebumen Kota", "Souvenir", ["batik", "kain", "lokal"], "Kain batik mini eksklusif."],
    ["Sabun Bunga Lavender", "Gombong", "Souvenir", ["sabun", "lavender", "aroma"], "Sabun bunga aroma lavender."],
    ["Gelas Mini Custom", "Kebumen Kota", "Souvenir", ["gelas", "custom", "mini"], "Gelas mini cetak nama."],
    ["Gantungan Kunci Akrilik", "Karanganyar", "Souvenir", ["gantungan", "akrilik", "lucu"], "Gantungan kunci akrilik lucu."],
    ["Bibit Tanaman Mini", "Prembun", "Souvenir", ["bibit", "tanaman", "hijau"], "Bibit tanaman dalam pot mini."],
  ],
  "Undangan Digital & Amplop": [
    ["Undangan Digital Floral", "Online", "Undangan", ["digital", "floral", "interaktif"], "Undangan web interaktif bertema bunga."],
    ["Undangan Wax Seal", "Kebumen Kota", "Undangan", ["cetak", "waxseal", "premium"], "Undangan cetak dengan segel lilin."],
    ["Undangan Royal Foil", "Online", "Undangan", ["foil", "royal", "gold"], "Sentuhan foil emas mewah."],
    ["Undangan Motion Video", "Online", "Undangan", ["motion", "video", "animasi"], "Undangan bergerak dengan animasi."],
    ["Amplop Digital QRIS", "Online", "Undangan", ["amplop", "qris", "digital"], "Amplop digital praktis."],
    ["Undangan Adat Jawa", "Online", "Undangan", ["adat", "jawa", "tradisional"], "Nuansa adat Jawa elegan."],
    ["Undangan Minimalis Typographic", "Online", "Undangan", ["minimalis", "typographic", "bersih"], "Desain tipografi minimalis bersih."],
    ["Undangan Islamic Syar'i", "Online", "Undangan", ["islamic", "syari", "elegan"], "Sentuhan islami yang menenangkan."],
    ["Undangan Hardcover Custom", "Kebumen Kota", "Undangan", ["hardcover", "custom", "premium"], "Undangan hardcover custom mewah."],
    ["Amplop Fisik Soft Touch", "Kebumen Kota", "Undangan", ["amplop", "softtouch", "fisik"], "Amplop fisik sentuhan lembut."],
  ],
  "Cute Illustrated Maps": [
    ["Denah Kartun Pantai", "Pantai Ayah", "Maps", ["kartun", "pantai", "lucu"], "Denah lucu bertema pantai."],
    ["Denah Botanical Pastel", "Kebumen Kota", "Maps", ["botanical", "pastel", "manis"], "Denah botanical warna pastel."],
    ["Denah Adat Jawa", "Gombong", "Maps", ["adat", "jawa", "kultural"], "Denah dengan ornamen adat."],
    ["Denah 3 Titik Lokasi", "Kebumen Kota", "Maps", ["multi", "titik", "lokasi"], "Panduan beberapa lokasi acara."],
    ["Denah Watercolor", "Karanganyar", "Maps", ["watercolor", "artistik", "lembut"], "Ilustrasi cat air lembut."],
    ["Denah + QR Navigasi", "Online", "Maps", ["qr", "navigasi", "gmaps"], "Integrasi QR Google Maps & Waze."],
    ["Denah Animasi Loading", "Online", "Maps", ["animasi", "loading", "interaktif"], "Denah dengan animasi loading lucu."],
    ["Denah Couple Character", "Kebumen Kota", "Maps", ["couple", "karakter", "lucu"], "Ilustrasi karakter pasangan lucu."],
    ["Denah Multi Venue", "Kebumen Kota", "Maps", ["multi", "venue", "panduan"], "Panduan beberapa lokasi acara."],
    ["Denah 3D Isometrik", "Online", "Maps", ["3d", "isometrik", "unik"], "Denah 3D isometrik yang unik."],
  ],
};

/** Ambil template portofolio untuk kategori; fallback ke kategori pertama. */
export function getPortfolioTemplates(category: string): PortfolioTemplate[] {
  return PORTFOLIO_TEMPLATES[category] ?? PORTFOLIO_TEMPLATES["Pre-wedding"];
}

/** Ambil template jasa untuk kategori; fallback ke kategori pertama. */
export function getServiceTemplates(category: string): ServiceTemplate[] {
  return SERVICE_TEMPLATES[category] ?? SERVICE_TEMPLATES["Pre-wedding"];
}

export { IMG };
